(function(g){var window=this;'use strict';var hKa=function(a,b){return g.Lb(a,b)},H4=function(a,b,c){a.l.set(b,c)},I4=function(a){H4(a,"zx",Math.floor(2147483648*Math.random()).toString(36)+Math.abs(Math.floor(2147483648*Math.random())^g.Sa()).toString(36));
return a},J4=function(a,b,c){Array.isArray(c)||(c=[String(c)]);
g.an(a.l,b,c)},iKa=function(a,b){var c=[];
g.aj(b,function(d){try{var e=g.Qn.prototype.l.call(this,d,!0)}catch(f){if("Storage: Invalid value was encountered"==f)return;throw f;}void 0===e?c.push(d):g.Pn(e)&&c.push(d)},a);
return c},jKa=function(a,b){b=iKa(a,b);
g.zb(b,function(c){g.Qn.prototype.remove.call(this,c)},a)},kKa=function(a){if(a.V){if(a.V.locationOverrideToken)return{locationOverrideToken:a.V.locationOverrideToken};
if(null!=a.V.latitudeE7&&null!=a.V.longitudeE7)return{latitudeE7:a.V.latitudeE7,longitudeE7:a.V.longitudeE7}}return null},lKa=function(a,b){g.fb(a,b)||a.push(b)},K4=function(a){var b=0,c;
for(c in a)b++;return b},mKa=function(a,b){b=b instanceof g.Bc?b:g.Ic(b,/^data:image\//i.test(b));
a.src=g.Cc(b)},nKa=function(a){try{return g.A.JSON.parse(a)}catch(b){}a=String(a);
if(/^\s*$/.test(a)?0:/^[\],:{}\s\u2028\u2029]*$/.test(a.replace(/\\["\\\/bfnrtu]/g,"@").replace(/(?:"[^"\\\n\r\u2028\u2029\x00-\x08\x0a-\x1f]*"|true|false|null|-?\d+(?:\.\d*)?(?:[eE][+\-]?\d+)?)[\s\u2028\u2029]*(?=:|,|]|}|$)/g,"]").replace(/(?:^|:|,)(?:[\s\u2028\u2029]*\[)+/g,"")))try{return eval("("+a+")")}catch(b){}throw Error("Invalid JSON string: "+a);},oKa=function(a){if(a.Bg&&"function"==typeof a.Bg)return a.Bg();
if("string"===typeof a)return a.split("");if(g.La(a)){for(var b=[],c=a.length,d=0;d<c;d++)b.push(a[d]);return b}return g.Ib(a)},pKa=function(a,b){if(a.forEach&&"function"==typeof a.forEach)a.forEach(b,void 0);
else if(g.La(a)||"string"===typeof a)g.zb(a,b,void 0);else{if(a.Ah&&"function"==typeof a.Ah)var c=a.Ah();else if(a.Bg&&"function"==typeof a.Bg)c=void 0;else if(g.La(a)||"string"===typeof a){c=[];for(var d=a.length,e=0;e<d;e++)c.push(e)}else c=g.Jb(a);d=oKa(a);e=d.length;for(var f=0;f<e;f++)b.call(void 0,d[f],c&&c[f],a)}},qKa=function(a,b,c,d){var e=new g.Pm(null,void 0);
a&&g.Qm(e,a);b&&g.Rm(e,b);c&&g.Sm(e,c);d&&(e.J=d);return e},L4=function(){},M4=function(a,b){g.Kq[a]=!0;
var c=g.Iq();c&&c.publish.apply(c,arguments);g.Kq[a]=!1},N4=function(a){this.app=this.name=this.id="";
this.type="REMOTE_CONTROL";this.obfuscatedGaiaId=this.avatar=this.username="";this.capabilities=new Set;this.experiments=new Set;this.theme="u";new g.Mm;a&&(this.id=a.id||a.name,this.name=a.name,this.app=a.app,this.type=a.type||"REMOTE_CONTROL",this.username=a.user||"",this.avatar=a.userAvatarUri||"",this.obfuscatedGaiaId=a.obfuscatedGaiaId||"",this.theme=a.theme||"u",rKa(this,a.capabilities||""),sKa(this,a.experiments||""))},rKa=function(a,b){a.capabilities.clear();
g.Je(b.split(","),g.Pa(hKa,tKa)).forEach(function(c){a.capabilities.add(c)})},sKa=function(a,b){a.experiments.clear();
b.split(",").forEach(function(c){a.experiments.add(c)})},O4=function(a){a=a||{};
this.name=a.name||"";this.id=a.id||a.screenId||"";this.token=a.token||a.loungeToken||"";this.uuid=a.uuid||a.dialId||"";this.idType=a.screenIdType||"normal"},P4=function(a,b){return!!b&&(a.id==b||a.uuid==b)},uKa=function(a){return{name:a.name,
screenId:a.id,loungeToken:a.token,dialId:a.uuid,screenIdType:a.idType}},vKa=function(a){return new O4(a)},wKa=function(a){return Array.isArray(a)?g.Oc(a,vKa):[]},Q4=function(a){return a?'{name:"'+a.name+'",id:'+a.id.substr(0,6)+"..,token:"+((a.token?".."+a.token.slice(-6):"-")+",uuid:"+(a.uuid?".."+a.uuid.slice(-6):"-")+",idType:"+a.idType+"}"):"null"},R4=function(a){return Array.isArray(a)?"["+g.Oc(a,Q4).join(",")+"]":"null"},S4=function(){return"xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx".replace(/[xy]/g,
function(a){var b=16*Math.random()|0;
return("x"==a?b:b&3|8).toString(16)})},xKa=function(a){return g.Oc(a,function(b){return{key:b.id,
name:b.name}})},T4=function(a,b){return g.bb(a,function(c){return c||b?!c!=!b?!1:c.id==b.id:!0})},U4=function(a,b){return g.bb(a,function(c){return P4(c,b)})},yKa=function(){var a=(0,g.Qu)();
a&&jKa(a,a.i.qk(!0))},V4=function(){var a=g.Tu("yt-remote-connected-devices")||[];
g.wb(a);return a},zKa=function(a){if(g.gb(a))return[];
var b=a[0].indexOf("#"),c=-1==b?a[0]:a[0].substring(0,b);return g.Oc(a,function(d,e){return 0==e?d:d.substring(c.length)})},AKa=function(a){g.Su("yt-remote-connected-devices",a,86400)},X4=function(){if(W4)return W4;
var a=g.Tu("yt-remote-device-id");a||(a=S4(),g.Su("yt-remote-device-id",a,31536E3));for(var b=V4(),c=1,d=a;g.fb(b,d);)c++,d=a+"#"+c;return W4=d},Y4=function(){var a=V4(),b=X4();
g.fb(a,b);g.Wu()&&g.yb(a,b);a=zKa(a);if(g.gb(a))try{g.zo("remote_sid")}catch(c){}else try{g.xo("remote_sid",a.join(","),-1)}catch(c){}},BKa=function(){return g.Tu("yt-remote-session-browser-channel")},CKa=function(){return g.Tu("yt-remote-local-screens")||[]},DKa=function(){g.Su("yt-remote-lounge-token-expiration",!0,86400)},EKa=function(a){5<a.length&&(a=a.slice(a.length-5));
var b=g.Oc(CKa(),function(d){return d.loungeToken}),c=g.Oc(a,function(d){return d.loungeToken});
g.hh(c,function(d){return!g.fb(b,d)})&&DKa();
g.Su("yt-remote-local-screens",a,31536E3)},FKa=function(a,b){g.Su("yt-remote-session-browser-channel",a);
g.Su("yt-remote-session-screen-id",b);a=V4();b=X4();g.fb(a,b)||a.push(b);AKa(a);Y4()},Z4=function(a){a||(g.Vu("yt-remote-session-screen-id"),g.Vu("yt-remote-session-video-id"));
Y4();a=V4();g.kb(a,X4());AKa(a)},GKa=function(){if(!$4){var a=g.$n();
a&&($4=new g.Kn(a))}},HKa=function(){GKa();
return $4?!!$4.get("yt-remote-use-staging-server"):!1},a5=function(){var a=window.navigator.userAgent.match(/Chrome\/([0-9]+)/);
return a?parseInt(a[1],10):0},IKa=function(a){return!!document.currentScript&&(-1!=document.currentScript.src.indexOf("?"+a)||-1!=document.currentScript.src.indexOf("&"+a))},JKa=function(){return"function"==typeof window.__onGCastApiAvailable?window.__onGCastApiAvailable:null},b5=function(a){a.length?KKa(a.shift(),function(){b5(a)}):c5()},LKa=function(a){return"chrome-extension://"+a+"/cast_sender.js"},KKa=function(a,b,c){var d=document.createElement("script");
d.onerror=b;c&&(d.onload=c);g.id(d,g.hg(a));(document.head||document.documentElement).appendChild(d)},MKa=function(){var a=a5(),b=[];
if(1<a){var c=a-1;b.push("//www.gstatic.com/eureka/clank/"+a+"/cast_sender.js");b.push("//www.gstatic.com/eureka/clank/"+c+"/cast_sender.js")}return b},c5=function(){var a=JKa();
a&&a(!1,"No cast extension found")},d5=function(){if(NKa){var a=2,b=JKa(),c=function(){a--;
0==a&&b&&b(!0)};
window.__onGCastApiAvailable=c;KKa("//www.gstatic.com/cast/sdk/libs/sender/1.0/cast_framework.js",c5,c)}},OKa=function(){d5();
var a=MKa();a.push("//www.gstatic.com/eureka/clank/cast_sender.js");b5(a)},QKa=function(){d5();
var a=MKa();a.push.apply(a,g.la(PKa.map(LKa)));a.push("//www.gstatic.com/eureka/clank/cast_sender.js");b5(a)},e5=function(a,b,c){g.F.call(this);
this.G=null!=c?(0,g.D)(a,c):a;this.Ff=b;this.C=(0,g.D)(this.PL,this);this.i=!1;this.l=0;this.u=this.yb=null;this.B=[]},f5=function(a,b,c){g.F.call(this);
this.B=null!=c?a.bind(c):a;this.Ff=b;this.u=null;this.i=!1;this.l=0;this.yb=null},g5=function(a){a.yb=g.Km(function(){a.yb=null;
a.i&&!a.l&&(a.i=!1,g5(a))},a.Ff);
var b=a.u;a.u=null;a.B.apply(null,b)},h5=function(a){if(g.A.JSON)try{return g.A.JSON.parse(a)}catch(b){}return nKa(a)},i5=function(){},j5=function(a,b){if("function"!==typeof a)throw Error("Fn must not be null and must be a function");
return g.A.setTimeout(function(){a()},b)},l5=function(a){k5.dispatchEvent(new RKa(k5,a))},RKa=function(a,b){g.Gl.call(this,"statevent",a);
this.stat=b},m5=function(){},SKa=function(){},UKa=function(a){return(a=TKa(a))?new ActiveXObject(a):new XMLHttpRequest},TKa=function(a){if(!a.l&&"undefined"==typeof XMLHttpRequest&&"undefined"!=typeof ActiveXObject){for(var b=["MSXML2.XMLHTTP.6.0",
"MSXML2.XMLHTTP.3.0","MSXML2.XMLHTTP","Microsoft.XMLHTTP"],c=0;c<b.length;c++){var d=b[c];try{return new ActiveXObject(d),a.l=d}catch(e){}}throw Error("Could not create ActiveXObject. ActiveX might be disabled, or MSXML might not be installed");}return a.l},n5=function(a,b,c,d){this.i=a;
this.l=b;this.L=c;this.J=d||1;this.C=45E3;this.B=new g.W_(this);this.u=new g.Jm;this.u.setInterval(250)},WKa=function(a,b,c){a.Lq=1;
a.Cl=I4(b.clone());a.Ko=c;a.G=!0;VKa(a,null)},o5=function(a,b,c,d,e){a.Lq=1;
a.Cl=I4(b.clone());a.Ko=null;a.G=c;e&&(a.XI=!1);VKa(a,d)},VKa=function(a,b){a.Cq=Date.now();
p5(a);a.Gm=a.Cl.clone();J4(a.Gm,"t",a.J);a.du=0;a.He=a.i.Dz(a.i.It()?b:null);0<a.Ey&&(a.Rw=new f5((0,g.D)(a.NJ,a,a.He),a.Ey));a.B.Oa(a.He,"readystatechange",a.eS);b=a.Vm?g.Sb(a.Vm):{};a.Ko?(a.Hx="POST",b["Content-Type"]="application/x-www-form-urlencoded",a.He.send(a.Gm,a.Hx,a.Ko,b)):(a.Hx="GET",a.XI&&!g.ze&&(b.Connection="close"),a.He.send(a.Gm,a.Hx,null,b));a.i.Fi(1)},ZKa=function(a,b,c){for(var d=!0;!a.Dn&&a.du<c.length;){var e=XKa(a,c);
if(e==q5){4==b&&(a.xl=4,l5(15),d=!1);break}else if(e==YKa){a.xl=4;l5(16);d=!1;break}else r5(a,e)}4==b&&0==c.length&&(a.xl=1,l5(17),d=!1);a.Pi=a.Pi&&d;d||(s5(a),t5(a))},XKa=function(a,b){var c=a.du,d=b.indexOf("\n",c);
if(-1==d)return q5;c=Number(b.substring(c,d));if(isNaN(c))return YKa;d+=1;if(d+c>b.length)return q5;b=b.substr(d,c);a.du=d+c;return b},aLa=function(a,b){a.Cq=Date.now();
p5(a);var c=b?window.location.hostname:"";a.Gm=a.Cl.clone();H4(a.Gm,"DOMAIN",c);H4(a.Gm,"t",a.J);try{a.Si=new ActiveXObject("htmlfile")}catch(m){s5(a);a.xl=7;l5(22);t5(a);return}var d="<html><body>";if(b){var e="";for(b=0;b<c.length;b++){var f=c.charAt(b);if("<"==f)f=e+"\\x3c";else if(">"==f)f=e+"\\x3e";else{if(f in u5)f=u5[f];else if(f in $Ka)f=u5[f]=$Ka[f];else{var h=f.charCodeAt(0);if(31<h&&127>h)var l=f;else{if(256>h){if(l="\\x",16>h||256<h)l+="0"}else l="\\u",4096>h&&(l+="0");l+=h.toString(16).toUpperCase()}f=
u5[f]=l}f=e+f}e=f}d+='<script>document.domain="'+e+'"\x3c/script>'}c=g.ed(g.dc("b/12014412"),d+"</body></html>");a.Si.open();a.Si.write(g.ad(c));a.Si.close();a.Si.parentWindow.m=(0,g.D)(a.CR,a);a.Si.parentWindow.d=(0,g.D)(a.jI,a,!0);a.Si.parentWindow.rpcClose=(0,g.D)(a.jI,a,!1);c=a.Si.createElement("DIV");a.Si.parentWindow.document.body.appendChild(c);d=g.Hc(a.Gm.toString());d=g.pd(g.Cc(d));d=g.ed(g.dc("b/12014412"),'<iframe src="'+d+'"></iframe>');g.fd(c,d);a.i.Fi(1)},p5=function(a){a.NC=Date.now()+
a.C;
bLa(a,a.C)},bLa=function(a,b){if(null!=a.Qq)throw Error("WatchDog timer not null");
a.Qq=j5((0,g.D)(a.KR,a),b)},v5=function(a){a.Qq&&(g.A.clearTimeout(a.Qq),a.Qq=null)},t5=function(a){a.i.ND()||a.Dn||a.i.Au(a)},s5=function(a){v5(a);
g.Di(a.Rw);a.Rw=null;a.u.stop();g.QEa(a.B);if(a.He){var b=a.He;a.He=null;b.abort();b.dispose()}a.Si&&(a.Si=null)},r5=function(a,b){try{a.i.cI(a,b),a.i.Fi(4)}catch(c){}},dLa=function(a,b,c,d,e){if(0==d)c(!1);
else{var f=e||0;d--;cLa(a,b,function(h){h?c(!0):g.A.setTimeout(function(){dLa(a,b,c,d,f)},f)})}},cLa=function(a,b,c){var d=new Image;
d.onload=function(){try{w5(d),c(!0)}catch(e){}};
d.onerror=function(){try{w5(d),c(!1)}catch(e){}};
d.onabort=function(){try{w5(d),c(!1)}catch(e){}};
d.ontimeout=function(){try{w5(d),c(!1)}catch(e){}};
g.A.setTimeout(function(){if(d.ontimeout)d.ontimeout()},b);
mKa(d,a)},w5=function(a){a.onload=null;
a.onerror=null;a.onabort=null;a.ontimeout=null},x5=function(a){g.$l.call(this);
this.headers=new g.Mm;this.ra=a||null;this.B=!1;this.ma=this.i=null;this.Fa=this.V="";this.G=0;this.u="";this.C=this.Ca=this.L=this.xa=!1;this.J=0;this.X=null;this.Ma="";this.Y=this.Ea=!1},eLa=function(a){return g.xe&&g.ae(9)&&"number"===typeof a.timeout&&void 0!==a.ontimeout},fLa=function(a){return"content-type"==a.toLowerCase()},hLa=function(a,b){a.B=!1;
a.i&&(a.C=!0,a.i.abort(),a.C=!1);a.u=b;a.G=5;gLa(a);y5(a)},gLa=function(a){a.xa||(a.xa=!0,a.dispatchEvent("complete"),a.dispatchEvent("error"))},jLa=function(a){if(a.B&&"undefined"!=typeof g.$_)if(a.ma[1]&&4==z5(a)&&2==a.getStatus())A5(a,"Local request error detected and ignored");
else if(a.L&&4==z5(a))g.Km(a.ZH,0,a);else if(a.dispatchEvent("readystatechange"),a.isComplete()){A5(a,"Request complete");a.B=!1;try{var b=a.getStatus();a:switch(b){case 200:case 201:case 202:case 204:case 206:case 304:case 1223:var c=!0;break a;default:c=!1}var d;if(!(d=c)){var e;if(e=0===b){var f=g.zd(1,String(a.V));if(!f&&g.A.self&&g.A.self.location){var h=g.A.self.location.protocol;f=h.substr(0,h.length-1)}e=!iLa.test(f?f.toLowerCase():"")}d=e}if(d)a.dispatchEvent("complete"),a.dispatchEvent("success");
else{a.G=6;try{var l=2<z5(a)?a.i.statusText:""}catch(m){l=""}a.u=l+" ["+a.getStatus()+"]";gLa(a)}}finally{y5(a)}}},y5=function(a,b){if(a.i){kLa(a);
var c=a.i,d=a.ma[0]?g.Ia:null;a.i=null;a.ma=null;b||a.dispatchEvent("ready");try{c.onreadystatechange=d}catch(e){}}},kLa=function(a){a.i&&a.Y&&(a.i.ontimeout=null);
a.X&&(g.A.clearTimeout(a.X),a.X=null)},z5=function(a){return a.i?a.i.readyState:0},B5=function(a){try{return a.i?a.i.responseText:""}catch(b){return""}},A5=function(a,b){return b+" ["+a.Fa+" "+a.V+" "+a.getStatus()+"]"},lLa=function(a){this.i=a;
this.l=new i5},mLa=function(a){var b=C5(a.i,a.Gr,"/mail/images/cleardot.gif");
I4(b);dLa(b.toString(),5E3,(0,g.D)(a.IM,a),3,2E3);a.Fi(1)},E5=function(a){var b=a.i.L;
if(null!=b)l5(5),b?(l5(11),D5(a.i,a,!1)):(l5(12),D5(a.i,a,!0));else if(a.Lg=new n5(a,void 0,void 0,void 0),a.Lg.Vm=a.Fy,b=a.i,b=C5(b,b.It()?a.vr:null,a.Gy),l5(5),!g.xe||g.be(10))J4(b,"TYPE","xmlhttp"),o5(a.Lg,b,!1,a.vr,!1);else{J4(b,"TYPE","html");var c=a.Lg;a=!!a.vr;c.Lq=3;c.Cl=I4(b.clone());aLa(c,a)}},F5=function(a,b,c){this.eb=1;
this.i=[];this.u=[];this.B=new i5;this.J=a||null;this.L=null!=b?b:null;this.C=c||!1},nLa=function(a,b){this.i=a;
this.map=b;this.context=null},oLa=function(a,b,c,d){g.Gl.call(this,"timingevent",a);
this.size=b;this.Bt=d},pLa=function(a){g.Gl.call(this,"serverreachability",a)},sLa=function(a){qLa(a);
if(3==a.eb){var b=a.Ts++,c=a.bv.clone();H4(c,"SID",a.l);H4(c,"RID",b);H4(c,"TYPE","terminate");G5(a,c);b=new n5(a,a.l,b,void 0);b.Lq=2;b.Cl=I4(c.clone());mKa(new Image,b.Cl.toString());b.Cq=Date.now();p5(b)}rLa(a)},tLa=function(a){a.eN(1,0);
a.bv=C5(a,null,a.Hy);H5(a)},qLa=function(a){a.Hl&&(a.Hl.abort(),a.Hl=null);
a.Ud&&(a.Ud.cancel(),a.Ud=null);a.vk&&(g.A.clearTimeout(a.vk),a.vk=null);I5(a);a.zg&&(a.zg.cancel(),a.zg=null);a.Pl&&(g.A.clearTimeout(a.Pl),a.Pl=null)},uLa=function(a,b){if(0==a.eb)throw Error("Invalid operation: sending map when state is closed");
a.i.push(new nLa(a.DO++,b));2!=a.eb&&3!=a.eb||H5(a)},vLa=function(a){var b=0;
a.Ud&&b++;a.zg&&b++;return b},H5=function(a){a.zg||a.Pl||(a.Pl=j5((0,g.D)(a.hI,a),0),a.Tp=0)},xLa=function(a,b){if(1==a.eb){if(!b){a.Ts=Math.floor(1E5*Math.random());
b=a.Ts++;var c=new n5(a,"",b,void 0);c.Vm=a.mj;var d=J5(a),e=a.bv.clone();H4(e,"RID",b);H4(e,"CVER","1");G5(a,e);WKa(c,e,d);a.zg=c;a.eb=2}}else 3==a.eb&&(b?wLa(a,b):0==a.i.length||a.zg||wLa(a))},wLa=function(a,b){if(b)if(6<a.En){a.i=a.u.concat(a.i);
a.u.length=0;var c=a.Ts-1;b=J5(a)}else c=b.L,b=b.Ko;else c=a.Ts++,b=J5(a);var d=a.bv.clone();H4(d,"SID",a.l);H4(d,"RID",c);H4(d,"AID",a.mq);G5(a,d);c=new n5(a,a.l,c,a.Tp+1);c.Vm=a.mj;c.setTimeout(1E4+Math.round(1E4*Math.random()));a.zg=c;WKa(c,d,b)},G5=function(a,b){a.yf&&(a=a.yf.JF())&&g.Bb(a,function(c,d){H4(b,d,c)})},J5=function(a){var b=Math.min(a.i.length,1E3),c=["count="+b];
if(6<a.En&&0<b){var d=a.i[0].i;c.push("ofs="+d)}else d=0;for(var e={},f=0;f<b;e={jp:e.jp},f++){e.jp=a.i[f].i;var h=a.i[f].map;e.jp=6>=a.En?f:e.jp-d;try{g.Bb(h,function(l){return function(m,n){c.push("req"+l.jp+"_"+n+"="+encodeURIComponent(m))}}(e))}catch(l){c.push("req"+e.jp+"_type="+encodeURIComponent("_badmap"))}}a.u=a.u.concat(a.i.splice(0,b));
return c.join("&")},yLa=function(a){a.Ud||a.vk||(a.G=1,a.vk=j5((0,g.D)(a.gI,a),0),a.Ip=0)},K5=function(a){if(a.Ud||a.vk||3<=a.Ip)return!1;
a.G++;a.vk=j5((0,g.D)(a.gI,a),zLa(a,a.Ip));a.Ip++;return!0},D5=function(a,b,c){a.Fx=c;
a.nj=b.ek;a.C||tLa(a)},I5=function(a){null!=a.Ln&&(g.A.clearTimeout(a.Ln),a.Ln=null)},zLa=function(a,b){var c=5E3+Math.floor(1E4*Math.random());
a.isActive()||(c*=2);return c*b},L5=function(a,b){if(2==b||9==b){var c=null;
a.yf&&(c=null);var d=(0,g.D)(a.IS,a);c||(c=new g.Pm("//www.google.com/images/cleardot.gif"),I4(c));cLa(c.toString(),1E4,d)}else l5(2);ALa(a,b)},ALa=function(a,b){a.eb=0;
a.yf&&a.yf.aF(b);rLa(a);qLa(a)},rLa=function(a){a.eb=0;
a.nj=-1;if(a.yf)if(0==a.u.length&&0==a.i.length)a.yf.nz();else{g.ob(a.u);var b=g.ob(a.i);a.u.length=0;a.i.length=0;a.yf.nz(b)}},C5=function(a,b,c){var d=g.Xm(c);
if(""!=d.i)b&&g.Rm(d,b+"."+d.i),g.Sm(d,d.u);else{var e=window.location;d=qKa(e.protocol,b?b+"."+e.hostname:e.hostname,+e.port,c)}a.Vr&&g.Bb(a.Vr,function(f,h){H4(d,h,f)});
H4(d,"VER",a.En);G5(a,d);return d},BLa=function(){},CLa=function(){this.i=[];
this.l=[]},DLa=function(a,b){this.action=a;
this.params=b||{}},M5=function(a,b){g.F.call(this);
this.i=new g.J(this.uR,0,this);g.H(this,this.i);this.Ff=5E3;this.l=0;if("function"===typeof a)b&&(a=(0,g.D)(a,b));else if(a&&"function"===typeof a.handleEvent)a=(0,g.D)(a.handleEvent,a);else throw Error("Invalid listener argument");this.u=a},N5=function(a,b,c,d,e){c=void 0===c?!1:c;
d=void 0===d?function(){return""}:d;
e=void 0===e?!1:e;this.ma=a;this.G=b;this.u=new g.Jn;this.l=new M5(this.oS,this);this.i=null;this.X=!1;this.C=null;this.V="";this.L=this.B=0;this.J=[];this.ra=c;this.Y=d;this.xa=e},ELa=function(a){return{firstTestResults:[""],
secondTestResults:!a.i.Fx,sessionId:a.i.l,arrayId:a.i.mq}},FLa=function(a,b){a.L=b||0;
a.l.stop();O5(a);a.i&&(3==a.i.getState()&&xLa(a.i),sLa(a.i));a.L=0},P5=function(a){return!!a.i&&3==a.i.getState()},O5=function(a){if(a.i){var b=a.Y(),c=a.i.mj||{};
b?c["x-youtube-lounge-xsrf-token"]=b:delete c["x-youtube-lounge-xsrf-token"];a.i.mj=c}},Q5=function(a){this.port=this.domain="";
this.i="/api/lounge";this.l=!0;a=a||document.location.href;var b=Number(g.zd(4,a))||"";b&&(this.port=":"+b);this.domain=g.Ad(a)||"";a=g.Uc;0<=a.search("MSIE")&&(a=a.match(/MSIE ([\d.]+)/)[1],0>g.zc(a,"10.0")&&(this.l=!1))},R5=function(a,b){var c=a.i;
a.l&&(c="https://"+a.domain+a.port+a.i);return g.Nd(c+b,{})},S5=function(a,b,c,d,e){a={format:"JSON",
method:"POST",context:a,timeout:5E3,withCredentials:!1,onSuccess:g.Pa(a.B,d,!0),onError:g.Pa(a.u,e),onTimeout:g.Pa(a.C,e)};c&&(a.postParams=c,a.headers={"Content-Type":"application/x-www-form-urlencoded"});return g.op(b,a)},JLa=function(){var a=GLa;
HLa();T5.push(a);ILa()},U5=function(a,b){HLa();
var c=KLa(a,String(b));g.gb(T5)?LLa(c):(ILa(),g.zb(T5,function(d){d(c)}))},HLa=function(){T5||(T5=g.Ha("yt.mdx.remote.debug.handlers_")||[],g.Ga("yt.mdx.remote.debug.handlers_",T5,void 0))},LLa=function(a){var b=(V5+1)%50;
V5=b;W5[b]=a;X5||(X5=49==b)},ILa=function(){var a=T5;
if(W5[0]){var b=X5?V5:-1;do{b=(b+1)%50;var c=W5[b];g.zb(a,function(d){d(c)})}while(b!=V5);
W5=Array(50);V5=-1;X5=!1}},KLa=function(a,b){var c=(Date.now()-MLa)/1E3;
c.toFixed&&(c=c.toFixed(3));var d=[];d.push("[",c+"s","] ");d.push("[","yt.mdx.remote","] ");d.push(a+": "+b,"\n");return d.join("")},Y5=function(a){g.O.call(this);
this.G=a;this.screens=[]},NLa=function(a,b){var c=a.get(b.uuid)||a.get(b.id);
if(c)return a=c.name,c.id=b.id||c.id,c.name=b.name,c.token=b.token,c.uuid=b.uuid||c.uuid,c.name!=a;a.screens.push(b);return!0},OLa=function(a,b){var c=a.screens.length!=b.length;
a.screens=g.Je(a.screens,function(f){return!!T4(b,f)});
for(var d=0,e=b.length;d<e;d++)c=NLa(a,b[d])||c;return c},PLa=function(a,b){var c=a.screens.length;
a.screens=g.Je(a.screens,function(d){return!(d||b?!d!=!b?0:d.id==b.id:1)});
return a.screens.length<c},Z5=function(a,b,c,d,e){g.O.call(this);
this.u=a;this.J=b;this.B=c;this.G=d;this.C=e;this.l=0;this.i=null;this.yb=NaN},a6=function(a){Y5.call(this,"LocalScreenService");
this.l=a;this.i=NaN;$5(this);this.info("Initializing with "+R4(this.screens))},QLa=function(a){if(a.screens.length){var b=g.Oc(a.screens,function(d){return d.id}),c=R5(a.l,"/pairing/get_lounge_token_batch");
S5(a.l,c,{screen_ids:b.join(",")},(0,g.D)(a.BN,a),(0,g.D)(a.AN,a))}},$5=function(a){if(g.Io("deprecate_pair_servlet_enabled"))return OLa(a,[]);
var b=wKa(CKa());b=g.Je(b,function(c){return!c.uuid});
return OLa(a,b)},b6=function(a,b){EKa(g.Oc(a.screens,uKa));
b&&DKa()},d6=function(a,b){g.O.call(this);
this.G=b;b=(b=g.Tu("yt-remote-online-screen-ids")||"")?b.split(","):[];for(var c={},d=this.G(),e=0,f=d.length;e<f;++e){var h=d[e].id;c[h]=g.fb(b,h)}this.i=c;this.C=a;this.u=this.B=NaN;this.l=null;c6("Initialized with "+g.Dj(this.i))},e6=function(a,b,c){var d=R5(a.C,"/pairing/get_screen_availability");
S5(a.C,d,{lounge_token:b.token},(0,g.D)(function(e){e=e.screens||[];for(var f=0,h=e.length;f<h;++f)if(e[f].loungeToken==b.token){c("online"==e[f].status);return}c(!1)},a),(0,g.D)(function(){c(!1)},a))},f6=function(a,b){a:if(K4(b)!=K4(a.i))var c=!1;
else{c=g.Jb(b);for(var d=0,e=c.length;d<e;++d)if(!a.i[c[d]]){c=!1;break a}c=!0}c||(c6("Updated online screens: "+g.Dj(a.i)),a.i=b,a.W("screenChange"));RLa(a)},g6=function(a){isNaN(a.u)||g.jp(a.u);
a.u=g.hp((0,g.D)(a.MB,a),0<a.B&&a.B<g.Sa()?2E4:1E4)},c6=function(a){U5("OnlineScreenService",a)},SLa=function(a){var b={};
g.zb(a.G(),function(c){c.token?b[c.token]=c.id:this.Hd("Requesting availability of screen w/o lounge token.")});
return b},RLa=function(a){a=g.Jb(g.Cb(a.i,function(b){return b}));
g.wb(a);a.length?g.Su("yt-remote-online-screen-ids",a.join(","),60):g.Vu("yt-remote-online-screen-ids")},h6=function(a,b){b=void 0===b?!1:b;
Y5.call(this,"ScreenService");this.B=a;this.J=b;this.i=this.l=null;this.u=[];this.C={};TLa(this)},VLa=function(a,b,c,d,e,f){a.info("getAutomaticScreenByIds "+c+" / "+b);
c||(c=a.C[b]);var h=a.Vg(),l=c?U4(h,c):null;c&&(a.J||l)||(l=U4(h,b));if(l){l.uuid=b;var m=i6(a,l);e6(a.i,m,function(n){e(n?m:null)})}else c?ULa(a,c,(0,g.D)(function(n){var p=i6(this,new O4({name:d,
screenId:c,loungeToken:n,dialId:b||""}));e6(this.i,p,function(r){e(r?p:null)})},a),f):e(null)},WLa=function(a,b){for(var c=0,d=a.screens.length;c<d;++c)if(a.screens[c].name==b)return a.screens[c];
return null},XLa=function(a,b,c){e6(a.i,b,c)},ULa=function(a,b,c,d){a.info("requestLoungeToken_ for "+b);
var e={postParams:{screen_ids:b},method:"POST",context:a,onSuccess:function(f,h){f=h&&h.screens||[];f[0]&&f[0].screenId==b?c(f[0].loungeToken):d(Error("Missing lounge token in token response"))},
onError:function(){d(Error("Request screen lounge token failed"))}};
g.op(R5(a.B,"/pairing/get_lounge_token_batch"),e)},YLa=function(a){a.screens=a.l.Vg();
var b=a.C,c={},d;for(d in b)c[b[d]]=d;b=0;for(d=a.screens.length;b<d;++b){var e=a.screens[b];e.uuid=c[e.id]||""}a.info("Updated manual screens: "+R4(a.screens))},TLa=function(a){j6(a);
a.l=new a6(a.B);a.l.subscribe("screenChange",(0,g.D)(a.HN,a));YLa(a);a.J||(a.u=wKa(g.Tu("yt-remote-automatic-screen-cache")||[]));j6(a);a.info("Initializing automatic screens: "+R4(a.u));a.i=new d6(a.B,(0,g.D)(a.Vg,a,!0));a.i.subscribe("screenChange",(0,g.D)(function(){this.W("onlineScreenChange")},a))},i6=function(a,b){var c=a.get(b.id);
c?(c.uuid=b.uuid,b=c):((c=U4(a.u,b.uuid))?(c.id=b.id,c.token=b.token,b=c):a.u.push(b),a.J||ZLa(a));j6(a);a.C[b.uuid]=b.id;g.Su("yt-remote-device-id-map",a.C,31536E3);return b},ZLa=function(a){a=g.Je(a.u,function(b){return"shortLived"!=b.idType});
g.Su("yt-remote-automatic-screen-cache",g.Oc(a,uKa))},j6=function(a){a.C=g.Tu("yt-remote-device-id-map")||{}},k6=function(a,b,c){g.O.call(this);
this.xa=c;this.u=a;this.i=b;this.B=null},l6=function(a,b){a.B=b;
a.W("sessionScreen",a.B)},$La=function(a,b){a.B&&(a.B.token=b,i6(a.u,a.B));
a.W("sessionScreen",a.B)},m6=function(a,b){U5(a.xa,b)},n6=function(a,b,c){k6.call(this,a,b,"CastSession");
var d=this;this.Ca=c;this.l=null;this.Y=(0,g.D)(this.UL,this);this.ra=(0,g.D)(this.OR,this);this.X=g.hp(function(){aMa(d,null)},12E4);
this.J=this.C=this.G=this.L=0;this.ma=!1;this.V="unknown"},o6=function(a,b){g.jp(a.J);
a.J=0;0==b?bMa(a):a.J=g.hp(function(){bMa(a)},b)},bMa=function(a){cMa(a,"getLoungeToken");
g.jp(a.C);a.C=g.hp(function(){dMa(a,null)},3E4)},cMa=function(a,b){a.info("sendYoutubeMessage_: "+b+" "+g.Dj(void 0));
var c={};c.type=b;a.l?a.l.sendMessage("urn:x-cast:com.google.youtube.mdx",c,g.Ia,(0,g.D)(function(){m6(this,"Failed to send message: "+b+".")},a)):m6(a,"Sending yt message without session: "+g.Dj(c))},p6=function(a,b){b?(a.info("onConnectedScreenId_: Received screenId: "+b),a.getScreen()&&a.getScreen().id==b||a.YF(b,function(c){l6(a,c)},function(){return a.Zf()},5)):a.Zf(Error("Waiting for session status timed out."))},fMa=function(a,b,c){a.info("onConnectedScreenData_: Received screenData: "+JSON.stringify(b));
var d=new O4(b);eMa(a,d,function(e){e?(a.ma=!0,i6(a.u,d),l6(a,d),a.V="unknown",o6(a,c)):(g.No(Error("CastSession, RemoteScreen from screenData: "+JSON.stringify(b)+" is not online.")),a.Zf())},5)},aMa=function(a,b){g.jp(a.X);
a.X=0;b?a.Ca.enableCastLoungeToken&&b.loungeToken?b.deviceId?a.getScreen()&&a.getScreen().uuid==b.deviceId||(b.loungeTokenRefreshIntervalMs?fMa(a,{name:a.i.friendlyName,screenId:b.screenId,loungeToken:b.loungeToken,dialId:b.deviceId,screenIdType:"shortLived"},b.loungeTokenRefreshIntervalMs):(g.No(Error("No loungeTokenRefreshIntervalMs presents in mdxSessionStatusData: "+JSON.stringify(b)+".")),p6(a,b.screenId))):(g.No(Error("No device id presents in mdxSessionStatusData: "+JSON.stringify(b)+".")),
p6(a,b.screenId)):p6(a,b.screenId):a.Zf(Error("Waiting for session status timed out."))},dMa=function(a,b){g.jp(a.C);
a.C=0;var c=null;if(b)if(b.loungeToken){var d;(null==(d=a.getScreen())?void 0:d.token)==b.loungeToken&&(c="staleLoungeToken")}else c="missingLoungeToken";else c="noLoungeTokenResponse";c?(a.info("Did not receive a new lounge token in onLoungeToken_ with data: "+(JSON.stringify(b)+", error: "+c)),a.V=c,o6(a,3E4)):($La(a,b.loungeToken),a.ma=!1,a.V="unknown",o6(a,b.loungeTokenRefreshIntervalMs))},eMa=function(a,b,c,d){g.jp(a.G);
a.G=0;XLa(a.u,b,function(e){e||0>d?c(e):a.G=g.hp(function(){eMa(a,b,c,d-1)},300)})},gMa=function(a){g.jp(a.L);
a.L=0;g.jp(a.G);a.G=0;g.jp(a.X);a.X=0;g.jp(a.C);a.C=0;g.jp(a.J);a.J=0},q6=function(a,b,c,d){k6.call(this,a,b,"DialSession");
this.Ea=d;this.l=this.L=null;this.ra="";this.Fa=c;this.Ba=null;this.X=g.Ia;this.V=NaN;this.Ca=(0,g.D)(this.VL,this);this.C=g.Ia;this.J=this.G=0;this.Y=!1;this.ma="unknown"},r6=function(a){var b;
return!!(a.Ea.enableDialLoungeToken&&(null==(b=a.l)?0:b.getDialAppInfo))},hMa=function(a){a.C=a.u.PD(a.ra,a.i.label,a.i.friendlyName,r6(a),function(b,c){a.C=g.Ia;
a.Y=!0;l6(a,b);"shortLived"==b.idType&&0<c&&s6(a,c)},function(b){a.C=g.Ia;
a.Zf(b)})},iMa=function(a){var b={};
b.pairingCode=a.ra;b.theme=a.Fa;HKa()&&(b.env_useStageMdx=1);return g.Jd(b)},t6=function(a){return new Promise(function(b){a.ra=S4();
if(a.Ba){var c=new chrome.cast.DialLaunchResponse(!0,iMa(a));b(c);hMa(a)}else a.X=function(){g.jp(a.V);a.X=function(){};
a.V=NaN;var d=new chrome.cast.DialLaunchResponse(!0,iMa(a));b(d);hMa(a)},a.V=g.hp(function(){a.X()},100)})},kMa=function(a,b,c){a.info("initOnConnectedScreenDataPromise_: Received screenData: "+JSON.stringify(b));
var d=new O4(b);return(new Promise(function(e){jMa(a,d,function(f){f?(a.Y=!0,i6(a.u,d),l6(a,d),s6(a,c)):g.No(Error("DialSession, RemoteScreen from screenData: "+JSON.stringify(b)+" is not online."));e(f)},5)})).then(function(e){return e?new chrome.cast.DialLaunchResponse(!1):t6(a)})},lMa=function(a,b){var c=a.L.receiver.label,d=a.i.friendlyName;
return(new Promise(function(e){VLa(a.u,c,b,d,function(f){f&&f.token&&l6(a,f);e(f)},function(f){m6(a,"Failed to get DIAL screen: "+f);
e(null)})})).then(function(e){return e&&e.token?new chrome.cast.DialLaunchResponse(!1):t6(a)})},jMa=function(a,b,c,d){g.jp(a.G);
a.G=0;XLa(a.u,b,function(e){e||0>d?c(e):a.G=g.hp(function(){jMa(a,b,c,d-1)},300)})},s6=function(a,b){a.info("getDialAppInfoWithTimeout_ "+b);
r6(a)&&(g.jp(a.J),a.J=0,0==b?mMa(a):a.J=g.hp(function(){mMa(a)},b))},mMa=function(a){r6(a)&&a.l.getDialAppInfo(function(b){a.info("getDialAppInfo dialLaunchData: "+JSON.stringify(b));
b=b.extraData||{};var c=null;if(b.loungeToken){var d;(null==(d=a.getScreen())?void 0:d.token)==b.loungeToken&&(c="staleLoungeToken")}else c="missingLoungeToken";c?(a.ma=c,s6(a,3E4)):(a.Y=!1,a.ma="unknown",$La(a,b.loungeToken),s6(a,b.loungeTokenRefreshIntervalMs))},function(b){a.info("getDialAppInfo error: "+b);
a.ma="noLoungeTokenResponse";s6(a,3E4)})},nMa=function(a){g.jp(a.G);
a.G=0;g.jp(a.J);a.J=0;a.C();a.C=function(){};
g.jp(a.V)},u6=function(a,b){k6.call(this,a,b,"ManualSession");
this.l=g.hp((0,g.D)(this.nq,this,null),150)},v6=function(a,b){g.O.call(this);
this.B=b;this.l=a;this.L=b.appId||"233637DE";this.C=b.theme||"cl";this.V=b.disableCastApi||!1;this.i=null;this.J=!1;this.u=[];this.G=(0,g.D)(this.KQ,this)},oMa=function(a,b){return b?g.bb(a.u,function(c){return P4(b,c.label)},a):null},w6=function(a){U5("Controller",a)},GLa=function(a){window.chrome&&chrome.cast&&chrome.cast.logMessage&&chrome.cast.logMessage(a)},x6=function(a){return a.J||!!a.u.length||!!a.i},y6=function(a,b,c){b!=a.i&&(g.Di(a.i),(a.i=b)?(c?a.W("yt-remote-cast2-receiver-resumed",
b.i):a.W("yt-remote-cast2-receiver-selected",b.i),b.subscribe("sessionScreen",(0,g.D)(a.fI,a,b)),b.getScreen()?a.W("yt-remote-cast2-session-change",b.getScreen()):c&&a.i.nq(null)):a.W("yt-remote-cast2-session-change",null))},pMa=function(a){var b=a.l.OD(),c=a.i&&a.i.i;
a=g.Oc(b,function(d){c&&P4(d,c.label)&&(c=null);var e=d.uuid?d.uuid:d.id,f=oMa(this,d);f?(f.label=e,f.friendlyName=d.name):(f=new chrome.cast.Receiver(e,d.name),f.receiverType=chrome.cast.ReceiverType.CUSTOM);return f},a);
c&&(c.receiverType!=chrome.cast.ReceiverType.CUSTOM&&(c=new chrome.cast.Receiver(c.label,c.friendlyName),c.receiverType=chrome.cast.ReceiverType.CUSTOM),a.push(c));return a},uMa=function(a,b,c,d){d.disableCastApi?z6("Cannot initialize because disabled by Mdx config."):qMa()?rMa(b,d)&&(A6(!0),window.chrome&&chrome.cast&&chrome.cast.isAvailable?sMa(a,c):(window.__onGCastApiAvailable=function(e,f){e?sMa(a,c):(B6("Failed to load cast API: "+f),C6(!1),A6(!1),g.Vu("yt-remote-cast-available"),g.Vu("yt-remote-cast-receiver"),
tMa(),c(!1))},d.loadCastApiSetupScript?g.Xu("https://www.gstatic.com/cv/js/sender/v1/cast_sender.js"):0<=window.navigator.userAgent.indexOf("Android")&&0<=window.navigator.userAgent.indexOf("Chrome/")&&window.navigator.presentation?60<=a5()&&OKa():!window.chrome||!window.navigator.presentation||0<=window.navigator.userAgent.indexOf("Edge")?c5():89<=a5()?QKa():(d5(),b5(PKa.map(LKa))))):z6("Cannot initialize because not running Chrome")},tMa=function(){z6("dispose");
var a=D6();a&&a.dispose();g.Ga("yt.mdx.remote.cloudview.instance_",null,void 0);vMa(!1);g.Nq(E6);E6.length=0},F6=function(){return!!g.Tu("yt-remote-cast-installed")},wMa=function(){var a=g.Tu("yt-remote-cast-receiver");
return a?a.friendlyName:null},xMa=function(){z6("clearCurrentReceiver");
g.Vu("yt-remote-cast-receiver")},yMa=function(){return F6()?D6()?D6().getCastSession():(B6("getCastSelector: Cast is not initialized."),null):(B6("getCastSelector: Cast API is not installed!"),null)},H6=function(){F6()?D6()?G6()?(z6("Requesting cast selector."),D6().requestSession()):(z6("Wait for cast API to be ready to request the session."),E6.push(g.Mq("yt-remote-cast2-api-ready",H6))):B6("requestCastSelector: Cast is not initialized."):B6("requestCastSelector: Cast API is not installed!")},I6=
function(a,b){G6()?D6().setConnectedScreenStatus(a,b):B6("setConnectedScreenStatus called before ready.")},qMa=function(){var a=0<=g.Uc.search(/ (CrMo|Chrome|CriOS)\//);
return g.TA||a},zMa=function(a,b){D6().init(a,b)},rMa=function(a,b){var c=!1;
D6()||(a=new v6(a,b),a.subscribe("yt-remote-cast2-availability-change",function(d){g.Su("yt-remote-cast-available",d);M4("yt-remote-cast2-availability-change",d)}),a.subscribe("yt-remote-cast2-receiver-selected",function(d){z6("onReceiverSelected: "+d.friendlyName);
g.Su("yt-remote-cast-receiver",d);M4("yt-remote-cast2-receiver-selected",d)}),a.subscribe("yt-remote-cast2-receiver-resumed",function(d){z6("onReceiverResumed: "+d.friendlyName);
g.Su("yt-remote-cast-receiver",d);M4("yt-remote-cast2-receiver-resumed",d)}),a.subscribe("yt-remote-cast2-session-change",function(d){z6("onSessionChange: "+Q4(d));
d||g.Vu("yt-remote-cast-receiver");M4("yt-remote-cast2-session-change",d)}),g.Ga("yt.mdx.remote.cloudview.instance_",a,void 0),c=!0);
z6("cloudview.createSingleton_: "+c);return c},D6=function(){return g.Ha("yt.mdx.remote.cloudview.instance_")},sMa=function(a,b){C6(!0);
A6(!1);zMa(a,function(c){c?(vMa(!0),g.Oq("yt-remote-cast2-api-ready")):(B6("Failed to initialize cast API."),C6(!1),g.Vu("yt-remote-cast-available"),g.Vu("yt-remote-cast-receiver"),tMa());b(c)})},z6=function(a){U5("cloudview",a)},B6=function(a){U5("cloudview",a)},C6=function(a){z6("setCastInstalled_ "+a);
g.Su("yt-remote-cast-installed",a)},G6=function(){return!!g.Ha("yt.mdx.remote.cloudview.apiReady_")},vMa=function(a){z6("setApiReady_ "+a);
g.Ga("yt.mdx.remote.cloudview.apiReady_",a,void 0)},A6=function(a){g.Ga("yt.mdx.remote.cloudview.initializing_",a,void 0)},J6=function(a){this.index=-1;
this.videoId=this.listId="";this.volume=this.playerState=-1;this.muted=!1;this.audioTrackId=null;this.G=this.J=0;this.trackData=null;this.hasNext=this.Dj=!1;this.L=this.C=this.i=this.B=0;this.u=NaN;this.l=!1;this.reset(a)},K6=function(a){a.audioTrackId=null;
a.trackData=null;a.playerState=-1;a.Dj=!1;a.hasNext=!1;a.J=0;a.G=g.Sa();a.B=0;a.i=0;a.C=0;a.L=0;a.u=NaN;a.l=!1},L6=function(a){return a.lc()?(g.Sa()-a.G)/1E3:0},M6=function(a,b){a.J=b;
a.G=g.Sa()},N6=function(a){switch(a.playerState){case 1:case 1081:return(g.Sa()-a.G)/1E3+a.J;
case -1E3:return 0}return a.J},O6=function(a,b,c){var d=a.videoId;
a.videoId=b;a.index=c;b!=d&&K6(a)},P6=function(a){var b={};
b.index=a.index;b.listId=a.listId;b.videoId=a.videoId;b.playerState=a.playerState;b.volume=a.volume;b.muted=a.muted;b.audioTrackId=a.audioTrackId;b.trackData=g.Tb(a.trackData);b.hasPrevious=a.Dj;b.hasNext=a.hasNext;b.playerTime=a.J;b.playerTimeAt=a.G;b.seekableStart=a.B;b.seekableEnd=a.i;b.duration=a.C;b.loadedTime=a.L;b.liveIngestionTime=a.u;return b},R6=function(a,b){g.O.call(this);
this.eb=0;this.u=a;this.C=[];this.B=new CLa;this.l=this.i=null;this.L=(0,g.D)(this.mP,this);this.G=(0,g.D)(this.Ws,this);this.J=(0,g.D)(this.lP,this);this.V=(0,g.D)(this.tP,this);var c=0;a?(c=a.getProxyState(),3!=c&&(a.subscribe("proxyStateChange",this.YB,this),AMa(this))):c=3;0!=c&&(b?this.YB(c):g.hp((0,g.D)(function(){this.YB(c)},this),0));
(a=yMa())&&Q6(this,a);this.subscribe("yt-remote-cast2-session-change",this.V)},S6=function(a){return new J6(a.u.getPlayerContextData())},AMa=function(a){g.zb("nowAutoplaying autoplayDismissed remotePlayerChange remoteQueueChange autoplayModeChange autoplayUpNext previousNextChange".split(" "),function(b){this.C.push(this.u.subscribe(b,g.Pa(this.HQ,b),this))},a)},BMa=function(a){g.zb(a.C,function(b){this.u.unsubscribeByKey(b)},a);
a.C.length=0},T6=function(a){return 1==a.getState()},U6=function(a,b){var c=a.B;
50>c.i.length+c.l.length&&a.B.l.push(b)},W6=function(a,b,c){var d=S6(a);
M6(d,c);-1E3!=d.playerState&&(d.playerState=b);V6(a,d)},X6=function(a,b,c){a.u.sendMessage(b,c)},V6=function(a,b){BMa(a);
a.u.setPlayerContextData(P6(b));AMa(a)},Q6=function(a,b){a.l&&(a.l.removeUpdateListener(a.L),a.l.removeMediaListener(a.G),a.Ws(null));
a.l=b;a.l&&(U5("CP","Setting cast session: "+a.l.sessionId),a.l.addUpdateListener(a.L),a.l.addMediaListener(a.G),a.l.media.length&&a.Ws(a.l.media[0]))},CMa=function(a){var b=a.i.media,c=a.i.customData;
if(b&&c){var d=S6(a);b.contentId!=d.videoId&&U5("CP","Cast changing video to: "+b.contentId);d.videoId=b.contentId;d.playerState=c.playerState;M6(d,a.i.getEstimatedTime());V6(a,d)}else U5("CP","No cast media video. Ignoring state update.")},Y6=function(a,b,c){return(0,g.D)(function(d){this.Hd("Failed to "+b+" with cast v2 channel. Error code: "+d.code);
d.code!=chrome.cast.ErrorCode.TIMEOUT&&(this.Hd("Retrying "+b+" using MDx browser channel."),X6(this,b,c))},a)},Z6=function(a,b,c){g.O.call(this);
this.C=NaN;this.ma=!1;this.L=this.J=this.X=this.Y=NaN;this.V=[];this.B=this.G=this.u=this.ac=this.i=null;this.xa=a;this.V.push(g.Np(window,"beforeunload",(0,g.D)(this.xN,this)));this.l=[];this.ac=new J6;this.Ca=b.id;this.ra=b.idType;this.i=DMa(this,c);this.i.subscribe("handlerOpened",this.qP,this);this.i.subscribe("handlerClosed",this.nP,this);this.i.subscribe("handlerError",this.oP,this);this.i.subscribe("handlerMessage",this.pP,this);this.i.gx(b.token);this.subscribe("remoteQueueChange",function(){var d=
this.ac.videoId;g.Wu()&&g.Su("yt-remote-session-video-id",d)},this)},$6=function(a){U5("conn",a)},DMa=function(a,b){return new N5(R5(a.xa,"/bc"),b,!1,function(){return a.TD()},"shortLived"==a.ra)},a7=function(a,b){a.W("proxyStateChange",b)},EMa=function(a){a.C=g.hp((0,g.D)(function(){$6("Connecting timeout");
this.Pp(1)},a),2E4)},b7=function(a){g.jp(a.C);
a.C=NaN},c7=function(a){g.jp(a.Y);
a.Y=NaN},FMa=function(a){d7(a);
a.X=g.hp((0,g.D)(function(){e7(this,"getNowPlaying")},a),2E4)},d7=function(a){g.jp(a.X);
a.X=NaN},HMa=function(a,b){b&&(b7(a),c7(a));
var c=P5(a.i)&&isNaN(a.C);b==c?b&&(a7(a,1),e7(a,"getSubtitlesTrack")):b?(a.XF()&&a.ac.reset(),a7(a,1),e7(a,"getNowPlaying"),GMa(a)):a.Pp(1)},IMa=function(a,b){var c=b.params.videoId;
delete b.params.videoId;c==a.ac.videoId&&(g.Ob(b.params)?a.ac.trackData=null:a.ac.trackData=b.params,a.W("remotePlayerChange"))},JMa=function(a,b){var c=b.params.videoId||b.params.video_id,d=parseInt(b.params.currentIndex,10);
a.ac.listId=b.params.listId||a.ac.listId;O6(a.ac,c,d);a.W("remoteQueueChange")},LMa=function(a,b){b.params=b.params||{};
JMa(a,b);KMa(a,b);a.W("autoplayDismissed")},KMa=function(a,b){var c=parseInt(b.params.currentTime||b.params.current_time,10);
M6(a.ac,isNaN(c)?0:c);c=parseInt(b.params.state,10);c=isNaN(c)?-1:c;-1==c&&-1E3==a.ac.playerState&&(c=-1E3);a.ac.playerState=c;c=Number(b.params.loadedTime);a.ac.L=isNaN(c)?0:c;c=Number(b.params.duration);a.ac.C=isNaN(c)?0:c;c=a.ac;var d=Number(b.params.liveIngestionTime);c.u=d;c.l=isNaN(d)?!1:!0;c=a.ac;d=Number(b.params.seekableStartTime);b=Number(b.params.seekableEndTime);c.B=isNaN(d)?0:d;c.i=isNaN(b)?0:b;1==a.ac.playerState?FMa(a):d7(a);a.W("remotePlayerChange")},MMa=function(a,b){if(-1E3!=a.ac.playerState){var c=
1085;
switch(parseInt(b.params.adState,10)){case 1:c=1081;break;case 2:c=1084;break;case 0:c=1083}a.ac.playerState=c;b=parseInt(b.params.currentTime,10);M6(a.ac,isNaN(b)?0:b);a.W("remotePlayerChange")}},NMa=function(a,b){var c="true"==b.params.muted;
a.ac.volume=parseInt(b.params.volume,10);a.ac.muted=c;a.W("remotePlayerChange")},OMa=function(a,b){a.G=b.params.videoId;
a.W("nowAutoplaying",parseInt(b.params.timeout,10))},PMa=function(a,b){var c="true"==b.params.hasNext;
a.ac.Dj="true"==b.params.hasPrevious;a.ac.hasNext=c;a.W("previousNextChange")},GMa=function(a){g.jp(a.L);
a.L=g.hp((0,g.D)(a.Pp,a,1),864E5)},e7=function(a,b,c){c?$6("Sending: action="+b+", params="+g.Dj(c)):$6("Sending: action="+b);
a.i.sendMessage(b,c)},f7=function(a){Y5.call(this,"ScreenServiceProxy");
this.Ef=a;this.i=[];this.i.push(this.Ef.$_s("screenChange",(0,g.D)(this.ZL,this)));this.i.push(this.Ef.$_s("onlineScreenChange",(0,g.D)(this.oQ,this)))},TMa=function(a,b){GKa();
if(!$4||!$4.get("yt-remote-disable-remote-module-for-dev")){b=g.M("MDX_CONFIG")||b;yKa();Y4();g7||(g7=new Q5(b?b.loungeApiHost:void 0),HKa()&&(g7.i="/api/loungedev"));h7||(h7=g.Ha("yt.mdx.remote.deferredProxies_")||[],g.Ga("yt.mdx.remote.deferredProxies_",h7,void 0));QMa();var c=i7();if(!c){var d=new h6(g7,b?b.disableAutomaticScreenCache||!1:!1);g.Ga("yt.mdx.remote.screenService_",d,void 0);c=i7();var e={};b&&(e={appId:b.appId,disableDial:b.disableDial,theme:b.theme,loadCastApiSetupScript:b.loadCastApiSetupScript,
disableCastApi:b.disableCastApi,enableDialLoungeToken:b.enableDialLoungeToken,enableCastLoungeToken:b.enableCastLoungeToken});uMa(a,d,function(f){f?j7()&&I6(j7(),"YouTube TV"):d.subscribe("onlineScreenChange",function(){M4("yt-remote-receiver-availability-change")})},e)}b&&!g.Ha("yt.mdx.remote.initialized_")&&(g.Ga("yt.mdx.remote.initialized_",!0,void 0),k7("Initializing: "+g.Dj(b)),l7.push(g.Mq("yt-remote-cast2-availability-change",function(){M4("yt-remote-receiver-availability-change")})),l7.push(g.Mq("yt-remote-cast2-receiver-selected",
function(){m7(null);
M4("yt-remote-auto-connect","cast-selector-receiver")})),l7.push(g.Mq("yt-remote-cast2-receiver-resumed",function(){M4("yt-remote-receiver-resumed","cast-selector-receiver")})),l7.push(g.Mq("yt-remote-cast2-session-change",RMa)),l7.push(g.Mq("yt-remote-connection-change",function(f){f?I6(j7(),"YouTube TV"):n7()||(I6(null,null),xMa())})),a=o7(),b.isAuto&&(a.id+="#dial"),e=b.capabilities||[],g.Io("desktop_enable_autoplay")&&e.push("atp"),0<e.length&&(a.capabilities=e),a.name=b.device,a.app=b.app,(b=
b.theme)&&(a.theme=b),k7(" -- with channel params: "+g.Dj(a)),a?(g.Su("yt-remote-session-app",a.app),g.Su("yt-remote-session-name",a.name)):(g.Vu("yt-remote-session-app"),g.Vu("yt-remote-session-name")),g.Ga("yt.mdx.remote.channelParams_",a,void 0),c.start(),j7()||SMa())}},UMa=function(){var a=i7().Ef.$_gos();
var b=p7();b&&q7()&&(T4(a,b)||a.push(b));return xKa(a)},r7=function(){var a=VMa();
!a&&F6()&&wMa()&&(a={key:"cast-selector-receiver",name:wMa()});return a},VMa=function(){var a=UMa(),b=p7();
b||(b=n7());return g.bb(a,function(c){return b&&P4(b,c.key)?!0:!1})},p7=function(){var a=j7();
if(!a)return null;var b=i7().Vg();return U4(b,a)},RMa=function(a){k7("remote.onCastSessionChange_: "+Q4(a));
if(a){var b=p7();if(b&&b.id==a.id){if(I6(b.id,"YouTube TV"),"shortLived"==a.idType&&(a=a.token))s7&&(s7.token=a),(b=q7())&&b.gx(a)}else b&&t7(),u7(a,1)}else q7()&&t7()},t7=function(){G6()?D6().stopSession():B6("stopSession called before API ready.");
var a=q7();a&&(a.disconnect(1),v7(null))},w7=function(){var a=q7();
return!!a&&3!=a.getProxyState()},k7=function(a){U5("remote",a)},i7=function(){if(!x7){var a=g.Ha("yt.mdx.remote.screenService_");
x7=a?new f7(a):null}return x7},j7=function(){return g.Ha("yt.mdx.remote.currentScreenId_")},WMa=function(a){g.Ga("yt.mdx.remote.currentScreenId_",a,void 0)},XMa=function(){return g.Ha("yt.mdx.remote.connectData_")},m7=function(a){g.Ga("yt.mdx.remote.connectData_",a,void 0)},q7=function(){return g.Ha("yt.mdx.remote.connection_")},v7=function(a){var b=q7();
m7(null);a||WMa("");g.Ga("yt.mdx.remote.connection_",a,void 0);h7&&(g.zb(h7,function(c){c(a)}),h7.length=0);
b&&!a?M4("yt-remote-connection-change",!1):!b&&a&&M4("yt-remote-connection-change",!0)},n7=function(){var a=g.Wu();
if(!a)return null;var b=i7();if(!b)return null;b=b.Vg();return U4(b,a)},u7=function(a,b){j7();
p7()&&p7();y7?s7=a:(WMa(a.id),a=new Z6(g7,a,o7()),a.connect(b,XMa()),a.subscribe("beforeDisconnect",function(c){M4("yt-remote-before-disconnect",c)}),a.subscribe("beforeDispose",function(){q7()&&(q7(),v7(null))}),a.subscribe("browserChannelAuthError",function(){var c=p7();
c&&"shortLived"==c.idType&&(G6()?D6().handleBrowserChannelAuthError():B6("refreshLoungeToken called before API ready."))}),v7(a))},SMa=function(){var a=n7();
a?(k7("Resume connection to: "+Q4(a)),u7(a,0)):(Z4(),xMa(),k7("Skipping connecting because no session screen found."))},QMa=function(){var a=o7();
if(g.Ob(a)){a=X4();var b=g.Tu("yt-remote-session-name")||"",c=g.Tu("yt-remote-session-app")||"";a={device:"REMOTE_CONTROL",id:a,name:b,app:c,mdxVersion:3};g.Ga("yt.mdx.remote.channelParams_",a,void 0)}},o7=function(){return g.Ha("yt.mdx.remote.channelParams_")||{}},z7=function(a,b,c){g.F.call(this);
var d=this;this.l=a;this.I=b;this.Pb=c;this.events=new g.YL(this);this.X=this.events.N(this.I,"onVolumeChange",function(e){YMa(d,e)});
this.C=!1;this.suggestion=null;this.G=new g.aJ(64);this.i=new g.J(this.fJ,500,this);this.u=new g.J(this.gJ,1E3,this);this.L=new e5(this.ZS,0,this);this.B={};this.V=new g.J(this.GJ,1E3,this);this.J=new f5(this.seekTo,1E3,this);this.Y=g.Ia;g.H(this,this.events);this.events.N(b,"onCaptionsTrackListChanged",this.WP);this.events.N(b,"captionschanged",this.jP);this.events.N(b,"captionssettingschanged",this.lJ);this.events.N(b,"videoplayerreset",this.Jw);this.events.N(b,"mdxautoplaycancel",function(){d.Pb.tF()});
a=this.Pb;a.Ga();a.subscribe("proxyStateChange",this.bI,this);a.subscribe("remotePlayerChange",this.gt,this);a.subscribe("remoteQueueChange",this.Jw,this);a.subscribe("previousNextChange",this.YH,this);a.subscribe("nowAutoplaying",this.SH,this);a.subscribe("autoplayDismissed",this.pH,this);g.H(this,this.i);g.H(this,this.u);g.H(this,this.L);g.H(this,this.V);g.H(this,this.J);this.lJ();this.Jw();this.gt()},YMa=function(a,b){if(A7(a)){a.Pb.unsubscribe("remotePlayerChange",a.gt,a);
var c=Math.round(b.volume);b=!!b.muted;var d=S6(a.Pb);if(c!==d.volume||b!==d.muted)a.Pb.setVolume(c,b),a.V.start();a.Pb.subscribe("remotePlayerChange",a.gt,a)}},ZMa=function(a){a.Tb(0);
a.i.stop();a.Hb(new g.aJ(64))},B7=function(a,b){if(A7(a)&&!a.C){var c=null;
b&&(c={style:a.I.getSubtitlesUserSettings()},g.Vb(c,b));a.Pb.SD(a.I.getVideoData(1).videoId,c);a.B=S6(a.Pb).trackData}},C7=function(a,b){var c=a.I.getPlaylist();
if(null===c||void 0===c?0:c.listId){var d=c.index;var e=c.listId.toString()}c=a.I.getVideoData(1);a.Pb.playVideo(c.videoId,b,d,e,c.playerParams,c.Ca,kKa(c));a.Hb(new g.aJ(1))},$Ma=function(a,b){if(b){var c=a.I.getOption("captions","tracklist",{pG:1});
c&&c.length?(a.I.setOption("captions","track",b),a.C=!1):(a.I.loadModule("captions"),a.C=!0)}else a.I.setOption("captions","track",{})},A7=function(a){return S6(a.Pb).videoId===a.I.getVideoData(1).videoId},D7=function(){g.V.call(this,{D:"div",
K:"ytp-mdx-manual-pairing-popup-dialog",U:{role:"dialog"},S:[{D:"div",K:"ytp-mdx-manual-pairing-popup-dialog-inner-content",S:[{D:"div",K:"ytp-mdx-manual-pairing-popup-title",oa:"Connecting to your TV on web using a code will be going away soon"},{D:"div",K:"ytp-mdx-manual-pairing-popup-buttons",S:[{D:"button",Da:["ytp-button","ytp-mdx-manual-pairing-popup-learn-more"],oa:"Learn more"},{D:"button",Da:["ytp-button","ytp-mdx-manual-pairing-popup-ok"],oa:"OK"}]}]}]});this.i=new g.HK(this,250);this.learnMoreButton=
this.Aa("ytp-mdx-manual-pairing-popup-learn-more");this.okButton=this.Aa("ytp-mdx-manual-pairing-popup-ok");g.H(this,this.i);this.N(this.learnMoreButton,"click",this.l);this.N(this.okButton,"click",this.u)},E7=function(){g.V.call(this,{D:"div",
K:"ytp-mdx-popup-dialog",U:{role:"dialog"},S:[{D:"div",K:"ytp-mdx-popup-dialog-inner-content",S:[{D:"div",K:"ytp-mdx-popup-title",oa:"You're signed out"},{D:"div",K:"ytp-mdx-popup-description",oa:"Videos you watch may be added to the TV's watch history and influence TV recommendations. To avoid this, cancel and sign in to YouTube on your computer."},{D:"div",K:"ytp-mdx-privacy-popup-buttons",S:[{D:"button",Da:["ytp-button","ytp-mdx-privacy-popup-cancel"],oa:"Cancel"},{D:"button",Da:["ytp-button",
"ytp-mdx-privacy-popup-confirm"],oa:"Confirm"}]}]}]});this.i=new g.HK(this,250);this.cancelButton=this.Aa("ytp-mdx-privacy-popup-cancel");this.confirmButton=this.Aa("ytp-mdx-privacy-popup-confirm");g.H(this,this.i);this.N(this.cancelButton,"click",this.l);this.N(this.confirmButton,"click",this.u)},F7=function(a){g.V.call(this,{D:"div",
K:"ytp-remote",S:[{D:"div",K:"ytp-remote-display-status",S:[{D:"div",K:"ytp-remote-display-status-icon",S:[g.Ima()]},{D:"div",K:"ytp-remote-display-status-text",oa:"{{statustext}}"}]}]});this.api=a;this.i=new g.HK(this,250);g.H(this,this.i);this.N(a,"presentingplayerstatechange",this.l);aNa(this,a.rb())},aNa=function(a,b){if(3===a.api.getPresentingPlayerType()){var c={RECEIVER_NAME:a.api.getOption("remote","currentReceiver").name};
b=g.U(b,128)?g.EH("Error on $RECEIVER_NAME",c):b.lc()||g.U(b,4)?g.EH("Playing on $RECEIVER_NAME",c):g.EH("Connected to $RECEIVER_NAME",c);a.Pa("statustext",b);a.i.show()}else a.i.hide()},G7=function(a,b){g.RO.call(this,"Play on",0,a,b);
this.I=a;this.Dm={};this.N(a,"onMdxReceiversChange",this.C);this.N(a,"presentingplayerstatechange",this.C);this.C()},H7=function(a){g.fM.call(this,a);
this.Ci={key:S4(),name:"This computer"};this.oh=null;this.subscriptions=[];this.BB=this.Pb=null;this.Dm=[this.Ci];this.Jl=this.Ci;this.Yc=new g.aJ(64);this.KG=0;this.Pe=-1;this.rq=null;this.ot=this.hw=!1;this.Xk=this.Aq=null;if(!g.jD(this.player.T())&&!g.kD(this.player.T())){a=this.player;var b=g.LL(a);b&&(b=b.Yl())&&(b=new G7(a,b),g.H(this,b));b=new F7(a);g.H(this,b);g.VL(a,b.element,4);this.Aq=new E7;g.H(this,this.Aq);g.VL(a,this.Aq.element,4);g.S(this.player.T().experiments,"pair_servlet_deprecation_warning_enabled")&&
!g.S(this.player.T().experiments,"deprecate_pair_servlet_enabled")&&(this.rq=new D7,g.H(this,this.rq),g.VL(a,this.rq.element,4));this.ot=!!n7();this.hw=!!g.Tu("yt-remote-manual-pairing-warning-shown")}},I7=function(a){a.Xk&&(a.player.removeEventListener("presentingplayerstatechange",a.Xk),a.Xk=null)},bNa=function(a,b,c){a.Yc=c;
a.player.W("presentingplayerstatechange",new g.qH(c,b))},cNa=function(a,b,c){var d=!1;
1===b?d=!a.ot:2===b&&(d=!a.hw);d&&g.sH(c,8)&&(a.player.pauseVideo(),I7(a))},J7=function(a,b){if(b.key!==a.Jl.key)if(b.key===a.Ci.key)t7();
else{if(a.rq&&!a.hw&&b!==a.Ci&&"cast-selector-receiver"!==b.key&&g.FD(a.player.T()))dNa(a);else{var c;(c=!g.S(a.player.T().experiments,"mdx_enable_privacy_disclosure_ui"))||(c=((c=g.M("PLAYER_CONFIG"))&&c.args&&void 0!==c.args.authuser?!0:!(!g.M("SESSION_INDEX")&&!g.M("LOGGED_IN")))||a.ot||!a.Aq);(c?0:g.FD(a.player.T())||g.JD(a.player.T()))&&eNa(a)}a.Jl=b;var d=a.player.getPlaylistId();c=a.player.getVideoData(1);var e=c.videoId;if(!d&&!e||(2===a.player.getAppState()||1===a.player.getAppState())&&
g.S(a.player.T().experiments,"should_clear_video_data_on_player_cued_unstarted"))a=null;else{var f=a.player.getPlaylist();if(f){var h=[];for(var l=0;l<f.length;l++)h[l]=f.bb(l).videoId}else h=[e];f=a.player.getCurrentTime(1);a={videoIds:h,listId:d,videoId:e,playerParams:c.playerParams,clickTrackingParams:c.Ca,index:Math.max(a.player.getPlaylistIndex(),0),currentTime:0===f?void 0:f};(c=kKa(c))&&(a.locationInfo=c)}k7("Connecting to: "+g.Dj(b));"cast-selector-receiver"==b.key?(m7(a||null),b=a||null,
G6()?D6().setLaunchParams(b):B6("setLaunchParams called before ready.")):!a&&w7()&&j7()==b.key?M4("yt-remote-connection-change",!0):(t7(),m7(a||null),a=i7().Vg(),(b=U4(a,b.key))&&u7(b,1))}},eNa=function(a){a.player.rb().lc()?a.player.pauseVideo():(a.Xk=function(b){cNa(a,1,b)},a.player.addEventListener("presentingplayerstatechange",a.Xk));
a.Aq&&a.Aq.Pc();q7()||(y7=!0)},dNa=function(a){a.player.rb().lc()?a.player.pauseVideo():(a.Xk=function(b){cNa(a,2,b)},a.player.addEventListener("presentingplayerstatechange",a.Xk));
a.rq&&a.rq.Pc();q7()||(y7=!0)},$Ka={"\x00":"\\0",
"\b":"\\b","\f":"\\f","\n":"\\n","\r":"\\r","\t":"\\t","\x0B":"\\x0B",'"':'\\"',"\\":"\\\\","<":"\\u003C"},u5={"'":"\\'"},fNa={},tKa={XT:"atp",I3:"ska",A2:"que",G0:"mus",H3:"sus",SX:"dsp",T2:"seq",j0:"mic",SW:"dpa",mU:"cds"},$4,W4="",NKa=IKa("loadCastFramework")||IKa("loadCastApplicationFramework"),PKa=["pkedcjkdefgpdelpbcmbmeomcjbeemfm","enhhojjnijigcajfphajepfemndkmdlo"];/*

 Copyright The Closure Library Authors.
 SPDX-License-Identifier: Apache-2.0
*/
g.Ta(e5,g.F);g.k=e5.prototype;g.k.yg=function(a){this.B=arguments;this.i=!1;this.yb?this.u=g.Sa()+this.Ff:this.yb=g.Km(this.C,this.Ff)};
g.k.stop=function(){this.yb&&(g.A.clearTimeout(this.yb),this.yb=null);this.u=null;this.i=!1;this.B=[]};
g.k.pause=function(){++this.l};
g.k.resume=function(){this.l&&(--this.l,!this.l&&this.i&&(this.i=!1,this.G.apply(null,this.B)))};
g.k.va=function(){this.stop();e5.Gd.va.call(this)};
g.k.PL=function(){this.yb&&(g.A.clearTimeout(this.yb),this.yb=null);this.u?(this.yb=g.Km(this.C,this.u-g.Sa()),this.u=null):this.l?this.i=!0:(this.i=!1,this.G.apply(null,this.B))};g.v(f5,g.F);g.k=f5.prototype;g.k.yg=function(a){this.u=arguments;this.yb||this.l?this.i=!0:g5(this)};
g.k.stop=function(){this.yb&&(g.A.clearTimeout(this.yb),this.yb=null,this.i=!1,this.u=null)};
g.k.pause=function(){this.l++};
g.k.resume=function(){this.l--;this.l||!this.i||this.yb||(this.i=!1,g5(this))};
g.k.va=function(){g.F.prototype.va.call(this);this.stop()};i5.prototype.stringify=function(a){return g.A.JSON.stringify(a,void 0)};
i5.prototype.parse=function(a){return g.A.JSON.parse(a,void 0)};var k5=new g.$l;g.v(RKa,g.Gl);m5.prototype.i=null;m5.prototype.getOptions=function(){var a;(a=this.i)||(a={},TKa(this)&&(a[0]=!0,a[1]=!0),a=this.i=a);return a};var K7;g.Ta(SKa,m5);K7=new SKa;g.k=n5.prototype;g.k.Vm=null;g.k.Pi=!1;g.k.Qq=null;g.k.NC=null;g.k.Cq=null;g.k.Lq=null;g.k.Cl=null;g.k.Gm=null;g.k.Ko=null;g.k.He=null;g.k.du=0;g.k.Si=null;g.k.Hx=null;g.k.xl=null;g.k.rr=-1;g.k.XI=!0;g.k.Dn=!1;g.k.Ey=0;g.k.Rw=null;var YKa={},q5={};g.k=n5.prototype;g.k.setTimeout=function(a){this.C=a};
g.k.eS=function(a){a=a.target;var b=this.Rw;b&&3==z5(a)?b.yg():this.NJ(a)};
g.k.NJ=function(a){try{if(a==this.He)a:{var b=z5(this.He),c=this.He.G,d=this.He.getStatus();if(g.xe&&!g.be(10)||g.ze&&!g.ae("420+")){if(4>b)break a}else if(3>b||3==b&&!g.mg&&!B5(this.He))break a;this.Dn||4!=b||7==c||(8==c||0>=d?this.i.Fi(3):this.i.Fi(2));v5(this);var e=this.He.getStatus();this.rr=e;var f=B5(this.He);(this.Pi=200==e)?(4==b&&s5(this),this.G?(ZKa(this,b,f),g.mg&&this.Pi&&3==b&&(this.B.Oa(this.u,"tick",this.ZR),this.u.start())):r5(this,f),this.Pi&&!this.Dn&&(4==b?this.i.Au(this):(this.Pi=
!1,p5(this)))):(400==e&&0<f.indexOf("Unknown SID")?(this.xl=3,l5(13)):(this.xl=0,l5(14)),s5(this),t5(this))}}catch(h){this.He&&B5(this.He)}finally{}};
g.k.ZR=function(){var a=z5(this.He),b=B5(this.He);this.du<b.length&&(v5(this),ZKa(this,a,b),this.Pi&&4!=a&&p5(this))};
g.k.CR=function(a){j5((0,g.D)(this.BR,this,a),0)};
g.k.BR=function(a){this.Dn||(v5(this),r5(this,a),p5(this))};
g.k.jI=function(a){j5((0,g.D)(this.AR,this,a),0)};
g.k.AR=function(a){this.Dn||(s5(this),this.Pi=a,this.i.Au(this),this.i.Fi(4))};
g.k.cancel=function(){this.Dn=!0;s5(this)};
g.k.KR=function(){this.Qq=null;var a=Date.now();0<=a-this.NC?(2!=this.Lq&&this.i.Fi(3),s5(this),this.xl=2,l5(18),t5(this)):bLa(this,this.NC-a)};
g.k.getLastError=function(){return this.xl};g.Ta(x5,g.$l);var iLa=/^https?$/i,gNa=["POST","PUT"];g.k=x5.prototype;
g.k.send=function(a,b,c,d){if(this.i)throw Error("[goog.net.XhrIo] Object is active with another request="+this.V+"; newUri="+a);b=b?b.toUpperCase():"GET";this.V=a;this.u="";this.G=0;this.Fa=b;this.xa=!1;this.B=!0;this.i=this.ra?UKa(this.ra):UKa(K7);this.ma=this.ra?this.ra.getOptions():K7.getOptions();this.i.onreadystatechange=(0,g.D)(this.ZH,this);try{L4(A5(this,"Opening Xhr")),this.Ca=!0,this.i.open(b,String(a),!0),this.Ca=!1}catch(f){L4(A5(this,"Error opening Xhr: "+f.message));hLa(this,f);return}a=
c||"";var e=this.headers.clone();d&&pKa(d,function(f,h){e.set(h,f)});
d=g.bb(e.Ah(),fLa);c=g.A.FormData&&a instanceof g.A.FormData;!g.fb(gNa,b)||d||c||e.set("Content-Type","application/x-www-form-urlencoded;charset=utf-8");e.forEach(function(f,h){this.i.setRequestHeader(h,f)},this);
this.Ma&&(this.i.responseType=this.Ma);"withCredentials"in this.i&&this.i.withCredentials!==this.Ea&&(this.i.withCredentials=this.Ea);try{kLa(this),0<this.J&&(this.Y=eLa(this.i),L4(A5(this,"Will abort after "+this.J+"ms if incomplete, xhr2 "+this.Y)),this.Y?(this.i.timeout=this.J,this.i.ontimeout=(0,g.D)(this.MD,this)):this.X=g.Km(this.MD,this.J,this)),L4(A5(this,"Sending request")),this.L=!0,this.i.send(a),this.L=!1}catch(f){L4(A5(this,"Send error: "+f.message)),hLa(this,f)}};
g.k.MD=function(){"undefined"!=typeof g.$_&&this.i&&(this.u="Timed out after "+this.J+"ms, aborting",this.G=8,A5(this,this.u),this.dispatchEvent("timeout"),this.abort(8))};
g.k.abort=function(a){this.i&&this.B&&(A5(this,"Aborting"),this.B=!1,this.C=!0,this.i.abort(),this.C=!1,this.G=a||7,this.dispatchEvent("complete"),this.dispatchEvent("abort"),y5(this))};
g.k.va=function(){this.i&&(this.B&&(this.B=!1,this.C=!0,this.i.abort(),this.C=!1),y5(this,!0));x5.Gd.va.call(this)};
g.k.ZH=function(){this.Ga()||(this.Ca||this.L||this.C?jLa(this):this.JQ())};
g.k.JQ=function(){jLa(this)};
g.k.isActive=function(){return!!this.i};
g.k.isComplete=function(){return 4==z5(this)};
g.k.getStatus=function(){try{return 2<z5(this)?this.i.status:-1}catch(a){return-1}};
g.k.getResponseHeader=function(a){if(this.i&&this.isComplete())return a=this.i.getResponseHeader(a),null===a?void 0:a};
g.k.getLastError=function(){return"string"===typeof this.u?this.u:String(this.u)};g.k=lLa.prototype;g.k.Fy=null;g.k.Lg=null;g.k.Sw=!1;g.k.hJ=null;g.k.Zu=null;g.k.PA=null;g.k.Gy=null;g.k.eb=null;g.k.ek=-1;g.k.vr=null;g.k.Gr=null;g.k.connect=function(a){this.Gy=a;a=C5(this.i,null,this.Gy);l5(3);this.hJ=Date.now();var b=this.i.J;null!=b?(this.vr=b[0],(this.Gr=b[1])?(this.eb=1,mLa(this)):(this.eb=2,E5(this))):(J4(a,"MODE","init"),this.Lg=new n5(this,void 0,void 0,void 0),this.Lg.Vm=this.Fy,o5(this.Lg,a,!1,null,!0),this.eb=0)};
g.k.IM=function(a){if(a)this.eb=2,E5(this);else{l5(4);var b=this.i;b.nj=b.Hl.ek;L5(b,9)}a&&this.Fi(2)};
g.k.Dz=function(a){return this.i.Dz(a)};
g.k.abort=function(){this.Lg&&(this.Lg.cancel(),this.Lg=null);this.ek=-1};
g.k.ND=function(){return!1};
g.k.cI=function(a,b){this.ek=a.rr;if(0==this.eb)if(b){try{var c=this.l.parse(b)}catch(d){a=this.i;a.nj=this.ek;L5(a,2);return}this.vr=c[0];this.Gr=c[1]}else a=this.i,a.nj=this.ek,L5(a,2);else if(2==this.eb)if(this.Sw)l5(7),this.PA=Date.now();else if("11111"==b){if(l5(6),this.Sw=!0,this.Zu=Date.now(),a=this.Zu-this.hJ,!g.xe||g.be(10)||500>a)this.ek=200,this.Lg.cancel(),l5(12),D5(this.i,this,!0)}else l5(8),this.Zu=this.PA=Date.now(),this.Sw=!1};
g.k.Au=function(){this.ek=this.Lg.rr;if(this.Lg.Pi)0==this.eb?this.Gr?(this.eb=1,mLa(this)):(this.eb=2,E5(this)):2==this.eb&&((!g.xe||g.be(10)?!this.Sw:200>this.PA-this.Zu)?(l5(11),D5(this.i,this,!1)):(l5(12),D5(this.i,this,!0)));else{0==this.eb?l5(9):2==this.eb&&l5(10);var a=this.i;this.Lg.getLastError();a.nj=this.ek;L5(a,2)}};
g.k.It=function(){return this.i.It()};
g.k.isActive=function(){return this.i.isActive()};
g.k.Fi=function(a){this.i.Fi(a)};g.k=F5.prototype;g.k.mj=null;g.k.Vr=null;g.k.zg=null;g.k.Ud=null;g.k.Hy=null;g.k.bv=null;g.k.PE=null;g.k.Bu=null;g.k.Ts=0;g.k.DO=0;g.k.yf=null;g.k.Pl=null;g.k.vk=null;g.k.Ln=null;g.k.Hl=null;g.k.Fx=null;g.k.mq=-1;g.k.JG=-1;g.k.nj=-1;g.k.Tp=0;g.k.Ip=0;g.k.En=8;g.Ta(oLa,g.Gl);g.Ta(pLa,g.Gl);g.k=F5.prototype;g.k.connect=function(a,b,c,d,e){l5(0);this.Hy=b;this.Vr=c||{};d&&void 0!==e&&(this.Vr.OSID=d,this.Vr.OAID=e);this.C?(j5((0,g.D)(this.gF,this,a),100),tLa(this)):this.gF(a)};
g.k.gF=function(a){this.Hl=new lLa(this);this.Hl.Fy=this.mj;this.Hl.l=this.B;this.Hl.connect(a)};
g.k.ND=function(){return 0==this.eb};
g.k.getState=function(){return this.eb};
g.k.hI=function(a){this.Pl=null;xLa(this,a)};
g.k.gI=function(){this.vk=null;this.Ud=new n5(this,this.l,"rpc",this.G);this.Ud.Vm=this.mj;this.Ud.Ey=0;var a=this.PE.clone();H4(a,"RID","rpc");H4(a,"SID",this.l);H4(a,"CI",this.Fx?"0":"1");H4(a,"AID",this.mq);G5(this,a);if(!g.xe||g.be(10))H4(a,"TYPE","xmlhttp"),o5(this.Ud,a,!0,this.Bu,!1);else{H4(a,"TYPE","html");var b=this.Ud,c=!!this.Bu;b.Lq=3;b.Cl=I4(a.clone());aLa(b,c)}};
g.k.cI=function(a,b){if(0!=this.eb&&(this.Ud==a||this.zg==a))if(this.nj=a.rr,this.zg==a&&3==this.eb)if(7<this.En){try{var c=this.B.parse(b)}catch(d){c=null}if(Array.isArray(c)&&3==c.length)if(a=c,0==a[0])a:{if(!this.vk){if(this.Ud)if(this.Ud.Cq+3E3<this.zg.Cq)I5(this),this.Ud.cancel(),this.Ud=null;else break a;K5(this);l5(19)}}else this.JG=a[1],0<this.JG-this.mq&&37500>a[2]&&this.Fx&&0==this.Ip&&!this.Ln&&(this.Ln=j5((0,g.D)(this.gP,this),6E3));else L5(this,11)}else b!=fNa.HW.i&&L5(this,11);else if(this.Ud==
a&&I5(this),!g.oc(b))for(a=this.B.parse(b),b=0;b<a.length;b++)c=a[b],this.mq=c[0],c=c[1],2==this.eb?"c"==c[0]?(this.l=c[1],this.Bu=c[2],c=c[3],null!=c?this.En=c:this.En=6,this.eb=3,this.yf&&this.yf.cF(),this.PE=C5(this,this.It()?this.Bu:null,this.Hy),yLa(this)):"stop"==c[0]&&L5(this,7):3==this.eb&&("stop"==c[0]?L5(this,7):"noop"!=c[0]&&this.yf&&this.yf.bF(c),this.Ip=0)};
g.k.gP=function(){null!=this.Ln&&(this.Ln=null,this.Ud.cancel(),this.Ud=null,K5(this),l5(20))};
g.k.Au=function(a){if(this.Ud==a){I5(this);this.Ud=null;var b=2}else if(this.zg==a)this.zg=null,b=1;else return;this.nj=a.rr;if(0!=this.eb)if(a.Pi)1==b?(b=k5,b.dispatchEvent(new oLa(b,a.Ko?a.Ko.length:0,Date.now()-a.Cq,this.Tp)),H5(this),this.u.length=0):yLa(this);else{var c=a.getLastError(),d;if(!(d=3==c||7==c||0==c&&0<this.nj)){if(d=1==b)this.zg||this.Pl||1==this.eb||2<=this.Tp?d=!1:(this.Pl=j5((0,g.D)(this.hI,this,a),zLa(this,this.Tp)),this.Tp++,d=!0);d=!(d||2==b&&K5(this))}if(d)switch(c){case 1:L5(this,
5);break;case 4:L5(this,10);break;case 3:L5(this,6);break;case 7:L5(this,12);break;default:L5(this,2)}}};
g.k.eN=function(a){if(!g.fb(arguments,this.eb))throw Error("Unexpected channel state: "+this.eb);};
g.k.IS=function(a){a?l5(2):(l5(1),ALa(this,8))};
g.k.Dz=function(a){if(a)throw Error("Can't create secondary domain capable XhrIo object.");a=new x5;a.Ea=!1;return a};
g.k.isActive=function(){return!!this.yf&&this.yf.isActive(this)};
g.k.Fi=function(a){var b=k5;b.dispatchEvent(new pLa(b,a))};
g.k.It=function(){return!(!g.xe||g.be(10))};
g.k=BLa.prototype;g.k.cF=function(){};
g.k.bF=function(){};
g.k.aF=function(){};
g.k.nz=function(){};
g.k.JF=function(){return{}};
g.k.isActive=function(){return!0};g.k=CLa.prototype;g.k.isEmpty=function(){return g.gb(this.i)&&g.gb(this.l)};
g.k.clear=function(){this.i=[];this.l=[]};
g.k.contains=function(a){return g.fb(this.i,a)||g.fb(this.l,a)};
g.k.remove=function(a){var b=this.i;var c=(0,g.VEa)(b,a);0<=c?(g.jb(b,c),b=!0):b=!1;return b||g.kb(this.l,a)};
g.k.Bg=function(){for(var a=[],b=this.i.length-1;0<=b;--b)a.push(this.i[b]);var c=this.l.length;for(b=0;b<c;++b)a.push(this.l[b]);return a};g.Ta(M5,g.F);g.k=M5.prototype;g.k.uR=function(){this.Ff=Math.min(3E5,2*this.Ff);this.u();this.l&&this.start()};
g.k.start=function(){var a=this.Ff+15E3*Math.random();g.kn(this.i,a);this.l=g.Sa()+a};
g.k.stop=function(){this.i.stop();this.l=0};
g.k.isActive=function(){return this.i.isActive()};
g.k.reset=function(){this.i.stop();this.Ff=5E3};g.Ta(N5,BLa);g.k=N5.prototype;g.k.subscribe=function(a,b,c){return this.u.subscribe(a,b,c)};
g.k.unsubscribe=function(a,b,c){return this.u.unsubscribe(a,b,c)};
g.k.Mf=function(a){return this.u.Mf(a)};
g.k.W=function(a,b){return this.u.W.apply(this.u,arguments)};
g.k.dispose=function(){this.X||(this.X=!0,g.Di(this.u),FLa(this),g.Di(this.l),this.l=null,this.Y=function(){return""})};
g.k.Ga=function(){return this.X};
g.k.connect=function(a,b,c){if(!this.i||2!=this.i.getState()){this.V="";this.l.stop();this.C=a||null;this.B=b||0;a=this.ma+"/test";b=this.ma+"/bind";var d=new F5(c?c.firstTestResults:null,c?c.secondTestResults:null,this.ra),e=this.i;e&&(e.yf=null);d.yf=this;this.i=d;O5(this);if(this.i){d=g.M("ID_TOKEN");var f=this.i.mj||{};d?f["x-youtube-identity-token"]=d:delete f["x-youtube-identity-token"];this.i.mj=f}e?(3!=e.getState()&&0==vLa(e)||e.getState(),this.i.connect(a,b,this.G,e.l,e.mq)):c?this.i.connect(a,
b,this.G,c.sessionId,c.arrayId):this.i.connect(a,b,this.G)}};
g.k.sendMessage=function(a,b){a={_sc:a};b&&g.Vb(a,b);this.l.isActive()||2==(this.i?this.i.getState():0)?this.J.push(a):P5(this)&&(O5(this),uLa(this.i,a))};
g.k.cF=function(){this.l.reset();this.C=null;this.B=0;if(this.J.length){var a=this.J;this.J=[];for(var b=0,c=a.length;b<c;++b)uLa(this.i,a[b])}this.W("handlerOpened")};
g.k.aF=function(a){var b=2==a&&401==this.i.nj;4==a||b||this.l.start();this.W("handlerError",a,b)};
g.k.nz=function(a){if(!this.l.isActive())this.W("handlerClosed");else if(a)for(var b=0,c=a.length;b<c;++b){var d=a[b].map;d&&this.J.push(d)}};
g.k.JF=function(){var a={v:2};this.V&&(a.gsessionid=this.V);0!=this.B&&(a.ui=""+this.B);0!=this.L&&(a.ui=""+this.L);this.C&&g.Vb(a,this.C);return a};
g.k.bF=function(a){"S"==a[0]?this.V=a[1]:"gracefulReconnect"==a[0]?(this.l.start(),sLa(this.i)):this.W("handlerMessage",new DLa(a[0],a[1]))};
g.k.gx=function(a){(this.G.loungeIdToken=a)||this.l.stop();if(this.xa&&this.i){var b=this.i.mj||{};a?b["X-YouTube-LoungeId-Token"]=a:delete b["X-YouTube-LoungeId-Token"];this.i.mj=b}};
g.k.oS=function(){this.l.isActive();0==vLa(this.i)&&this.connect(this.C,this.B)};Q5.prototype.B=function(a,b,c,d){b?a(d):a({text:c.responseText})};
Q5.prototype.u=function(a,b){a(Error("Request error: "+b.status))};
Q5.prototype.C=function(a){a(Error("request timed out"))};var MLa=Date.now(),T5=null,W5=Array(50),V5=-1,X5=!1;g.Ta(Y5,g.O);Y5.prototype.Vg=function(){return this.screens};
Y5.prototype.contains=function(a){return!!T4(this.screens,a)};
Y5.prototype.get=function(a){return a?U4(this.screens,a):null};
Y5.prototype.info=function(a){U5(this.G,a)};g.v(Z5,g.O);g.k=Z5.prototype;g.k.start=function(){!this.i&&isNaN(this.yb)&&this.rI()};
g.k.stop=function(){this.i&&(this.i.abort(),this.i=null);isNaN(this.yb)||(g.jp(this.yb),this.yb=NaN)};
g.k.va=function(){this.stop();g.O.prototype.va.call(this)};
g.k.rI=function(){this.yb=NaN;this.i=g.op(R5(this.u,"/pairing/get_screen"),{method:"POST",postParams:{pairing_code:this.J},timeout:5E3,onSuccess:(0,g.D)(this.RL,this),onError:(0,g.D)(this.QL,this),onTimeout:(0,g.D)(this.SL,this)})};
g.k.RL=function(a,b){this.i=null;a=b.screen||{};a.dialId=this.B;a.name=this.G;b=-1;this.C&&a.shortLivedLoungeToken&&a.shortLivedLoungeToken.value&&a.shortLivedLoungeToken.refreshIntervalMs&&(a.screenIdType="shortLived",a.loungeToken=a.shortLivedLoungeToken.value,b=a.shortLivedLoungeToken.refreshIntervalMs);this.W("pairingComplete",new O4(a),b)};
g.k.QL=function(a){this.i=null;a.status&&404==a.status?this.l>=hNa.length?this.W("pairingFailed",Error("DIAL polling timed out")):(a=hNa[this.l],this.yb=g.hp((0,g.D)(this.rI,this),a),this.l++):this.W("pairingFailed",Error("Server error "+a.status))};
g.k.SL=function(){this.i=null;this.W("pairingFailed",Error("Server not responding"))};
var hNa=[2E3,2E3,1E3,1E3,1E3,2E3,2E3,5E3,5E3,1E4];g.Ta(a6,Y5);g.k=a6.prototype;g.k.start=function(){$5(this)&&this.W("screenChange");!g.Tu("yt-remote-lounge-token-expiration")&&QLa(this);g.jp(this.i);this.i=g.hp((0,g.D)(this.start,this),1E4)};
g.k.add=function(a,b){$5(this);NLa(this,a);b6(this,!1);this.W("screenChange");b(a);a.token||QLa(this)};
g.k.remove=function(a,b){var c=$5(this);PLa(this,a)&&(b6(this,!1),c=!0);b(a);c&&this.W("screenChange")};
g.k.Dx=function(a,b,c,d){var e=$5(this),f=this.get(a.id);f?(f.name!=b&&(f.name=b,b6(this,!1),e=!0),c(a)):d(Error("no such local screen."));e&&this.W("screenChange")};
g.k.va=function(){g.jp(this.i);a6.Gd.va.call(this)};
g.k.BN=function(a){$5(this);var b=this.screens.length;a=a&&a.screens||[];for(var c=0,d=a.length;c<d;++c){var e=a[c],f=this.get(e.screenId);f&&(f.token=e.loungeToken,--b)}b6(this,!b);b&&U5(this.G,"Missed "+b+" lounge tokens.")};
g.k.AN=function(a){U5(this.G,"Requesting lounge tokens failed: "+a)};g.v(d6,g.O);g.k=d6.prototype;g.k.start=function(){var a=parseInt(g.Tu("yt-remote-fast-check-period")||"0",10);(this.B=g.Sa()-144E5<a?0:a)?g6(this):(this.B=g.Sa()+3E5,g.Su("yt-remote-fast-check-period",this.B),this.MB())};
g.k.isEmpty=function(){return g.Ob(this.i)};
g.k.update=function(){c6("Updating availability on schedule.");var a=this.G(),b=g.Cb(this.i,function(c,d){return c&&!!U4(a,d)},this);
f6(this,b)};
g.k.va=function(){g.jp(this.u);this.u=NaN;this.l&&(this.l.abort(),this.l=null);g.O.prototype.va.call(this)};
g.k.MB=function(){g.jp(this.u);this.u=NaN;this.l&&this.l.abort();var a=SLa(this);if(K4(a)){var b=R5(this.C,"/pairing/get_screen_availability");this.l=S5(this.C,b,{lounge_token:g.Jb(a).join(",")},(0,g.D)(this.dR,this,a),(0,g.D)(this.cR,this))}else f6(this,{}),g6(this)};
g.k.dR=function(a,b){this.l=null;var c=g.Jb(SLa(this));if(g.xb(c,g.Jb(a))){b=b.screens||[];c={};for(var d=0,e=b.length;d<e;++d)c[a[b[d].loungeToken]]="online"==b[d].status;f6(this,c);g6(this)}else this.Hd("Changing Screen set during request."),this.MB()};
g.k.cR=function(a){this.Hd("Screen availability failed: "+a);this.l=null;g6(this)};
g.k.Hd=function(a){U5("OnlineScreenService",a)};g.Ta(h6,Y5);g.k=h6.prototype;g.k.start=function(){this.l.start();this.i.start();this.screens.length&&(this.W("screenChange"),this.i.isEmpty()||this.W("onlineScreenChange"))};
g.k.add=function(a,b,c){this.l.add(a,b,c)};
g.k.remove=function(a,b,c){this.l.remove(a,b,c);this.i.update()};
g.k.Dx=function(a,b,c,d){this.l.contains(a)?this.l.Dx(a,b,c,d):(a="Updating name of unknown screen: "+a.name,U5(this.G,a),d(Error(a)))};
g.k.Vg=function(a){return a?this.screens:g.nb(this.screens,g.Je(this.u,function(b){return!this.contains(b)},this))};
g.k.OD=function(){return g.Je(this.Vg(!0),function(a){return!!this.i.i[a.id]},this)};
g.k.PD=function(a,b,c,d,e,f){var h=this;this.info("getDialScreenByPairingCode "+a+" / "+b);var l=new Z5(this.B,a,b,c,d);l.subscribe("pairingComplete",function(m,n){g.Di(l);e(i6(h,m),n)});
l.subscribe("pairingFailed",function(m){g.Di(l);f(m)});
l.start();return(0,g.D)(l.stop,l)};
g.k.TL=function(a,b,c,d){g.op(R5(this.B,"/pairing/get_screen"),{method:"POST",postParams:{pairing_code:a},timeout:5E3,onSuccess:(0,g.D)(function(e,f){e=new O4(f.screen||{});if(!e.name||WLa(this,e.name)){a:{f=e.name;for(var h=2,l=b(f,h);WLa(this,l);){h++;if(20<h)break a;l=b(f,h)}f=l}e.name=f}c(i6(this,e))},this),
onError:(0,g.D)(function(e){d(Error("pairing request failed: "+e.status))},this),
onTimeout:(0,g.D)(function(){d(Error("pairing request timed out."))},this)})};
g.k.va=function(){g.Di(this.l);g.Di(this.i);h6.Gd.va.call(this)};
g.k.HN=function(){YLa(this);this.W("screenChange");this.i.update()};
h6.prototype.dispose=h6.prototype.dispose;g.Ta(k6,g.O);g.k=k6.prototype;g.k.getScreen=function(){return this.B};
g.k.Zf=function(a){this.Ga()||(a&&m6(this,""+a),this.B=null,this.W("sessionScreen",null))};
g.k.info=function(a){U5(this.xa,a)};
g.k.QD=function(){return null};
g.k.WB=function(a){var b=this.i;a?(b.displayStatus=new chrome.cast.ReceiverDisplayStatus(a,[]),b.displayStatus.showStop=!0):b.displayStatus=null;chrome.cast.setReceiverDisplayStatus(b,(0,g.D)(function(){this.info("Updated receiver status for "+b.friendlyName+": "+a)},this),(0,g.D)(function(){m6(this,"Failed to update receiver status for: "+b.friendlyName)},this))};
g.k.va=function(){this.WB("");k6.Gd.va.call(this)};g.v(n6,k6);g.k=n6.prototype;g.k.VB=function(a){if(this.l){if(this.l==a)return;m6(this,"Overriding cast session with new session object");gMa(this);this.ma=!1;this.V="unknown";this.l.removeUpdateListener(this.Y);this.l.removeMessageListener("urn:x-cast:com.google.youtube.mdx",this.ra)}this.l=a;this.l.addUpdateListener(this.Y);this.l.addMessageListener("urn:x-cast:com.google.youtube.mdx",this.ra);cMa(this,"getMdxSessionStatus")};
g.k.nq=function(a){this.info("launchWithParams no-op for Cast: "+g.Dj(a))};
g.k.stop=function(){this.l?this.l.stop((0,g.D)(function(){this.Zf()},this),(0,g.D)(function(){this.Zf(Error("Failed to stop receiver app."))},this)):this.Zf(Error("Stopping cast device without session."))};
g.k.WB=function(){};
g.k.va=function(){this.info("disposeInternal");gMa(this);this.l&&(this.l.removeUpdateListener(this.Y),this.l.removeMessageListener("urn:x-cast:com.google.youtube.mdx",this.ra));this.l=null;k6.prototype.va.call(this)};
g.k.OR=function(a,b){if(!this.Ga())if(b)if(b=h5(b),g.Ma(b))switch(a=""+b.type,b=b.data||{},this.info("onYoutubeMessage_: "+a+" "+g.Dj(b)),a){case "mdxSessionStatus":aMa(this,b);break;case "loungeToken":dMa(this,b);break;default:m6(this,"Unknown youtube message: "+a)}else m6(this,"Unable to parse message.");else m6(this,"No data in message.")};
g.k.YF=function(a,b,c,d){g.jp(this.L);this.L=0;VLa(this.u,this.i.label,a,this.i.friendlyName,(0,g.D)(function(e){e?b(e):0<=d?(m6(this,"Screen "+a+" appears to be offline. "+d+" retries left."),this.L=g.hp((0,g.D)(this.YF,this,a,b,c,d-1),300)):c(Error("Unable to fetch screen."))},this),c)};
g.k.QD=function(){return this.l};
g.k.UL=function(a){this.Ga()||a||(m6(this,"Cast session died."),this.Zf())};g.v(q6,k6);g.k=q6.prototype;g.k.VB=function(a){this.l=a;this.l.addUpdateListener(this.Ca)};
g.k.nq=function(a){this.Ba=a;this.X()};
g.k.stop=function(){nMa(this);this.l?this.l.stop((0,g.D)(this.Zf,this,null),(0,g.D)(this.Zf,this,"Failed to stop DIAL device.")):this.Zf()};
g.k.va=function(){nMa(this);this.l&&this.l.removeUpdateListener(this.Ca);this.l=null;k6.prototype.va.call(this)};
g.k.VL=function(a){this.Ga()||a||(m6(this,"DIAL session died."),this.C(),this.C=g.Ia,this.Zf())};g.v(u6,k6);u6.prototype.stop=function(){this.Zf()};
u6.prototype.VB=function(){};
u6.prototype.nq=function(){g.jp(this.l);this.l=NaN;var a=U4(this.u.Vg(),this.i.label);a?l6(this,a):this.Zf(Error("No such screen"))};
u6.prototype.va=function(){g.jp(this.l);this.l=NaN;k6.prototype.va.call(this)};g.v(v6,g.O);g.k=v6.prototype;
g.k.init=function(a,b){chrome.cast.timeout.requestSession=3E4;var c=new chrome.cast.SessionRequest(this.L);this.V||(c.dialRequest=new chrome.cast.DialRequest("YouTube"));var d=chrome.cast.AutoJoinPolicy.TAB_AND_ORIGIN_SCOPED;a=a?chrome.cast.DefaultActionPolicy.CAST_THIS_TAB:chrome.cast.DefaultActionPolicy.CREATE_SESSION;var e=(0,g.D)(this.NQ,this);c=new chrome.cast.ApiConfig(c,(0,g.D)(this.dI,this),e,d,a);c.customDialLaunchCallback=(0,g.D)(this.AP,this);chrome.cast.initialize(c,(0,g.D)(function(){this.Ga()||
(chrome.cast.addReceiverActionListener(this.G),JLa(),this.l.subscribe("onlineScreenChange",(0,g.D)(this.RD,this)),this.u=pMa(this),chrome.cast.setCustomReceivers(this.u,g.Ia,(0,g.D)(function(f){this.Hd("Failed to set initial custom receivers: "+g.Dj(f))},this)),this.W("yt-remote-cast2-availability-change",x6(this)),b(!0))},this),(0,g.D)(function(f){this.Hd("Failed to initialize API: "+g.Dj(f));
b(!1)},this))};
g.k.tS=function(a,b){w6("Setting connected screen ID: "+a+" -> "+b);if(this.i){var c=this.i.getScreen();if(!a||c&&c.id!=a)w6("Unsetting old screen status: "+this.i.i.friendlyName),y6(this,null)}if(a&&b){if(!this.i){c=U4(this.l.Vg(),a);if(!c){w6("setConnectedScreenStatus: Unknown screen.");return}if("shortLived"==c.idType){w6("setConnectedScreenStatus: Screen with id type to be short lived.");return}a=oMa(this,c);a||(w6("setConnectedScreenStatus: Connected receiver not custom..."),a=new chrome.cast.Receiver(c.uuid?
c.uuid:c.id,c.name),a.receiverType=chrome.cast.ReceiverType.CUSTOM,this.u.push(a),chrome.cast.setCustomReceivers(this.u,g.Ia,(0,g.D)(function(d){this.Hd("Failed to set initial custom receivers: "+g.Dj(d))},this)));
w6("setConnectedScreenStatus: new active receiver: "+a.friendlyName);y6(this,new u6(this.l,a),!0)}this.i.WB(b)}else w6("setConnectedScreenStatus: no screen.")};
g.k.uS=function(a){this.Ga()?this.Hd("Setting connection data on disposed cast v2"):this.i?this.i.nq(a):this.Hd("Setting connection data without a session")};
g.k.XL=function(){this.Ga()?this.Hd("Stopping session on disposed cast v2"):this.i?(this.i.stop(),y6(this,null)):w6("Stopping non-existing session")};
g.k.requestSession=function(){chrome.cast.requestSession((0,g.D)(this.dI,this),(0,g.D)(this.gR,this))};
g.k.va=function(){this.l.unsubscribe("onlineScreenChange",(0,g.D)(this.RD,this));window.chrome&&chrome.cast&&chrome.cast.removeReceiverActionListener(this.G);var a=GLa,b=g.Ha("yt.mdx.remote.debug.handlers_");g.kb(b||[],a);g.Di(this.i);g.O.prototype.va.call(this)};
g.k.Hd=function(a){U5("Controller",a)};
g.k.fI=function(a,b){this.i==a&&(b||y6(this,null),this.W("yt-remote-cast2-session-change",b))};
g.k.KQ=function(a,b){if(!this.Ga())if(a)switch(a.friendlyName=chrome.cast.unescape(a.friendlyName),w6("onReceiverAction_ "+a.label+" / "+a.friendlyName+"-- "+b),b){case chrome.cast.ReceiverAction.CAST:if(this.i)if(this.i.i.label!=a.label)w6("onReceiverAction_: Stopping active receiver: "+this.i.i.friendlyName),this.i.stop();else{w6("onReceiverAction_: Casting to active receiver.");this.i.getScreen()&&this.W("yt-remote-cast2-session-change",this.i.getScreen());break}switch(a.receiverType){case chrome.cast.ReceiverType.CUSTOM:y6(this,
new u6(this.l,a));break;case chrome.cast.ReceiverType.DIAL:y6(this,new q6(this.l,a,this.C,this.B));break;case chrome.cast.ReceiverType.CAST:y6(this,new n6(this.l,a,this.B));break;default:this.Hd("Unknown receiver type: "+a.receiverType)}break;case chrome.cast.ReceiverAction.STOP:this.i&&this.i.i.label==a.label?this.i.stop():this.Hd("Stopping receiver w/o session: "+a.friendlyName)}else this.Hd("onReceiverAction_ called without receiver.")};
g.k.AP=function(a){if(this.Ga())return Promise.reject(Error("disposed"));var b=a.receiver;b.receiverType!=chrome.cast.ReceiverType.DIAL&&(this.Hd("Not DIAL receiver: "+b.friendlyName),b.receiverType=chrome.cast.ReceiverType.DIAL);var c=this.i?this.i.i:null;if(!c||c.label!=b.label)return this.Hd("Receiving DIAL launch request for non-clicked DIAL receiver: "+b.friendlyName),Promise.reject(Error("illegal DIAL launch"));if(c&&c.label==b.label&&c.receiverType!=chrome.cast.ReceiverType.DIAL){if(this.i.getScreen())return w6("Reselecting dial screen."),
this.W("yt-remote-cast2-session-change",this.i.getScreen()),Promise.resolve(new chrome.cast.DialLaunchResponse(!1));this.Hd('Changing CAST intent from "'+c.receiverType+'" to "dial" for '+b.friendlyName);y6(this,new q6(this.l,b,this.C,this.B))}b=this.i;b.L=a;b.L.appState==chrome.cast.DialAppState.RUNNING?(a=b.L.extraData||{},c=a.screenId||null,r6(b)&&a.loungeToken?a.loungeTokenRefreshIntervalMs?a=kMa(b,{name:b.i.friendlyName,screenId:a.screenId,loungeToken:a.loungeToken,dialId:b.L.receiver.label,
screenIdType:"shortLived"},a.loungeTokenRefreshIntervalMs):(g.No(Error("No loungeTokenRefreshIntervalMs presents in additionalData: "+JSON.stringify(a)+".")),a=lMa(b,c)):a=lMa(b,c)):a=t6(b);return a};
g.k.dI=function(a){if(!this.Ga()){w6("New cast session ID: "+a.sessionId);var b=a.receiver;if(b.receiverType!=chrome.cast.ReceiverType.CUSTOM){if(!this.i)if(b.receiverType==chrome.cast.ReceiverType.CAST)w6("Got resumed cast session before resumed mdx connection."),b.friendlyName=chrome.cast.unescape(b.friendlyName),y6(this,new n6(this.l,b,this.B),!0);else{this.Hd("Got non-cast session without previous mdx receiver event, or mdx resume.");return}var c=this.i.i,d=U4(this.l.Vg(),c.label);d&&P4(d,b.label)&&
c.receiverType!=chrome.cast.ReceiverType.CAST&&b.receiverType==chrome.cast.ReceiverType.CAST&&(w6("onSessionEstablished_: manual to cast session change "+b.friendlyName),g.Di(this.i),this.i=new n6(this.l,b,this.B),this.i.subscribe("sessionScreen",(0,g.D)(this.fI,this,this.i)),this.i.nq(null));this.i.VB(a)}}};
g.k.WL=function(){return this.i?this.i.QD():null};
g.k.gR=function(a){this.Ga()||(this.Hd("Failed to estabilish a session: "+g.Dj(a)),a.code!=chrome.cast.ErrorCode.CANCEL&&y6(this,null))};
g.k.NQ=function(a){w6("Receiver availability updated: "+a);if(!this.Ga()){var b=x6(this);this.J=a==chrome.cast.ReceiverAvailability.AVAILABLE;x6(this)!=b&&this.W("yt-remote-cast2-availability-change",x6(this))}};
g.k.RD=function(){this.Ga()||(this.u=pMa(this),w6("Updating custom receivers: "+g.Dj(this.u)),chrome.cast.setCustomReceivers(this.u,g.Ia,(0,g.D)(function(){this.Hd("Failed to set custom receivers.")},this)),this.W("yt-remote-cast2-availability-change",x6(this)))};
v6.prototype.setLaunchParams=v6.prototype.uS;v6.prototype.setConnectedScreenStatus=v6.prototype.tS;v6.prototype.stopSession=v6.prototype.XL;v6.prototype.getCastSession=v6.prototype.WL;v6.prototype.requestSession=v6.prototype.requestSession;v6.prototype.init=v6.prototype.init;v6.prototype.dispose=v6.prototype.dispose;var E6=[];g.k=J6.prototype;
g.k.reset=function(a){this.listId="";this.index=-1;this.videoId="";K6(this);this.volume=-1;this.muted=!1;a&&(this.index=a.index,this.listId=a.listId,this.videoId=a.videoId,this.playerState=a.playerState,this.volume=a.volume,this.muted=a.muted,this.audioTrackId=a.audioTrackId,this.trackData=a.trackData,this.Dj=a.hasPrevious,this.hasNext=a.hasNext,this.J=a.playerTime,this.G=a.playerTimeAt,this.B=a.seekableStart,this.i=a.seekableEnd,this.C=a.duration,this.L=a.loadedTime,this.u=a.liveIngestionTime,this.l=
!isNaN(this.u))};
g.k.lc=function(){return 1==this.playerState};
g.k.isAdPlaying=function(){return 1081==this.playerState};
g.k.getDuration=function(){return this.l?this.C+L6(this):this.C};
g.k.clone=function(){return new J6(P6(this))};g.v(R6,g.O);g.k=R6.prototype;g.k.getState=function(){return this.eb};
g.k.play=function(){T6(this)?(this.i?this.i.play(null,g.Ia,Y6(this,"play")):X6(this,"play"),W6(this,1,N6(S6(this))),this.W("remotePlayerChange")):U6(this,this.play)};
g.k.pause=function(){T6(this)?(this.i?this.i.pause(null,g.Ia,Y6(this,"pause")):X6(this,"pause"),W6(this,2,N6(S6(this))),this.W("remotePlayerChange")):U6(this,this.pause)};
g.k.seekTo=function(a){if(T6(this)){if(this.i){var b=S6(this),c=new chrome.cast.media.SeekRequest;c.currentTime=a;b.lc()||3==b.playerState?c.resumeState=chrome.cast.media.ResumeState.PLAYBACK_START:c.resumeState=chrome.cast.media.ResumeState.PLAYBACK_PAUSE;this.i.seek(c,g.Ia,Y6(this,"seekTo",{newTime:a}))}else X6(this,"seekTo",{newTime:a});W6(this,3,a);this.W("remotePlayerChange")}else U6(this,g.Pa(this.seekTo,a))};
g.k.stop=function(){if(T6(this)){this.i?this.i.stop(null,g.Ia,Y6(this,"stopVideo")):X6(this,"stopVideo");var a=S6(this);a.index=-1;a.videoId="";K6(a);V6(this,a);this.W("remotePlayerChange")}else U6(this,this.stop)};
g.k.setVolume=function(a,b){if(T6(this)){var c=S6(this);if(this.l){if(c.volume!=a){var d=Math.round(a)/100;this.l.setReceiverVolumeLevel(d,(0,g.D)(function(){U5("CP","set receiver volume: "+d)},this),(0,g.D)(function(){this.Hd("failed to set receiver volume.")},this))}c.muted!=b&&this.l.setReceiverMuted(b,(0,g.D)(function(){U5("CP","set receiver muted: "+b)},this),(0,g.D)(function(){this.Hd("failed to set receiver muted.")},this))}else{var e={volume:a,
muted:b};-1!=c.volume&&(e.delta=a-c.volume);X6(this,"setVolume",e)}c.muted=b;c.volume=a;V6(this,c)}else U6(this,g.Pa(this.setVolume,a,b))};
g.k.SD=function(a,b){if(T6(this)){var c=S6(this);a={videoId:a};b&&(c.trackData={trackName:b.name,languageCode:b.languageCode,sourceLanguageCode:b.translationLanguage?b.translationLanguage.languageCode:"",languageName:b.languageName,kind:b.kind},a.style=g.Dj(b.style),g.Vb(a,c.trackData));X6(this,"setSubtitlesTrack",a);V6(this,c)}else U6(this,g.Pa(this.SD,a,b))};
g.k.setAudioTrack=function(a,b){T6(this)?(b=b.getLanguageInfo().getId(),X6(this,"setAudioTrack",{videoId:a,audioTrackId:b}),a=S6(this),a.audioTrackId=b,V6(this,a)):U6(this,g.Pa(this.setAudioTrack,a,b))};
g.k.playVideo=function(a,b,c,d,e,f,h){var l=S6(this);c=c||0;var m={videoId:a,currentIndex:c};O6(l,a,c);void 0!==b&&(M6(l,b),m.currentTime=b);void 0!==d&&(m.listId=d);null!=e&&(m.playerParams=e);null!=f&&(m.clickTrackingParams=f);null!=h&&(m.locationInfo=g.Dj(h));X6(this,"setPlaylist",m);d||V6(this,l)};
g.k.Nw=function(a,b){if(T6(this)){if(a&&b){var c=S6(this);O6(c,a,b);V6(this,c)}X6(this,"previous")}else U6(this,g.Pa(this.Nw,a,b))};
g.k.nextVideo=function(a,b){if(T6(this)){if(a&&b){var c=S6(this);O6(c,a,b);V6(this,c)}X6(this,"next")}else U6(this,g.Pa(this.nextVideo,a,b))};
g.k.tF=function(){T6(this)?X6(this,"dismissAutoplay"):U6(this,this.tF)};
g.k.dispose=function(){if(3!=this.eb){var a=this.eb;this.eb=3;this.W("proxyStateChange",a,this.eb)}g.O.prototype.dispose.call(this)};
g.k.va=function(){BMa(this);this.u=null;this.B.clear();Q6(this,null);g.O.prototype.va.call(this)};
g.k.YB=function(a){if((a!=this.eb||2==a)&&3!=this.eb&&0!=a){var b=this.eb;this.eb=a;this.W("proxyStateChange",b,a);if(1==a)for(;!this.B.isEmpty();)b=a=this.B,g.gb(b.i)&&(b.i=b.l,b.i.reverse(),b.l=[]),a.i.pop().apply(this);else 3==a&&this.dispose()}};
g.k.HQ=function(a,b){this.W(a,b)};
g.k.mP=function(a){if(!a)this.Ws(null),Q6(this,null);else if(this.l.receiver.volume){a=this.l.receiver.volume;var b=S6(this),c=Math.round(100*a.level||0);if(b.volume!=c||b.muted!=a.muted)U5("CP","Cast volume update: "+a.level+(a.muted?" muted":"")),b.volume=c,b.muted=!!a.muted,V6(this,b)}};
g.k.Ws=function(a){U5("CP","Cast media: "+!!a);this.i&&this.i.removeUpdateListener(this.J);if(this.i=a)this.i.addUpdateListener(this.J),CMa(this),this.W("remotePlayerChange")};
g.k.lP=function(a){a?(CMa(this),this.W("remotePlayerChange")):this.Ws(null)};
g.k.rC=function(){X6(this,"sendDebugCommand",{debugCommand:"stats4nerds "})};
g.k.tP=function(){var a=yMa();a&&Q6(this,a)};
g.k.Hd=function(a){U5("CP",a)};g.v(Z6,g.O);g.k=Z6.prototype;
g.k.connect=function(a,b){if(b){var c=b.listId,d=b.videoId,e=b.playerParams,f=b.clickTrackingParams,h=b.index,l={videoId:d},m=b.currentTime;b=b.locationInfo;void 0!==m&&(l.currentTime=5>=m?0:m);e&&(l.playerParams=e);b&&(l.locationInfo=b);f&&(l.clickTrackingParams=f);c&&(l.listId=c);void 0!==h&&(l.currentIndex=h);c&&(this.ac.listId=c);this.ac.videoId=d;this.ac.index=h||0;this.ac.state=3;M6(this.ac,m);this.B="UNSUPPORTED";$6("Connecting with setPlaylist and params: "+g.Dj(l));this.i.connect({method:"setPlaylist",
params:g.Dj(l)},a,BKa())}else $6("Connecting without params"),this.i.connect({},a,BKa());EMa(this)};
g.k.gx=function(a){this.i.gx(a)};
g.k.dispose=function(){this.Ga()||(this.W("beforeDispose"),a7(this,3));g.O.prototype.dispose.call(this)};
g.k.va=function(){b7(this);d7(this);c7(this);g.jp(this.J);this.J=NaN;g.jp(this.L);this.L=NaN;this.u=null;g.Op(this.V);this.V.length=0;this.i.dispose();g.O.prototype.va.call(this);this.B=this.G=this.l=this.ac=this.i=null};
g.k.xN=function(){this.Pp(2)};
g.k.qP=function(){$6("Channel opened");this.ma&&(this.ma=!1,c7(this),this.Y=g.hp((0,g.D)(function(){$6("Timing out waiting for a screen.");this.Pp(1)},this),15E3));
FKa(ELa(this.i),this.Ca)};
g.k.nP=function(){$6("Channel closed");isNaN(this.C)?Z4(!0):Z4();this.dispose()};
g.k.oP=function(a,b){Z4();isNaN(this.ys())?(b&&"shortLived"==this.ra&&this.W("browserChannelAuthError",a),$6("Channel error: "+a+" without reconnection"),this.dispose()):(this.ma=!0,$6("Channel error: "+a+" with reconnection in "+this.ys()+" ms"),a7(this,2))};
g.k.pP=function(a){a.params?$6("Received: action="+a.action+", params="+g.Dj(a.params)):$6("Received: action="+a.action+" {}");switch(a.action){case "loungeStatus":a=h5(a.params.devices);this.l=g.Oc(a,function(c){return new N4(c)});
a=!!g.bb(this.l,function(c){return"LOUNGE_SCREEN"==c.type});
HMa(this,a);break;case "loungeScreenDisconnected":g.lb(this.l,function(c){return"LOUNGE_SCREEN"==c.type});
HMa(this,!1);break;case "remoteConnected":var b=new N4(h5(a.params.device));g.bb(this.l,function(c){return b?c.id==b.id:!1})||lKa(this.l,b);
break;case "remoteDisconnected":b=new N4(h5(a.params.device));g.lb(this.l,function(c){return b?c.id==b.id:!1});
break;case "gracefulDisconnect":break;case "playlistModified":JMa(this,a);break;case "nowPlaying":LMa(this,a);break;case "onStateChange":KMa(this,a);break;case "onAdStateChange":MMa(this,a);break;case "onVolumeChanged":NMa(this,a);break;case "onSubtitlesTrackChanged":IMa(this,a);break;case "nowAutoplaying":OMa(this,a);break;case "autoplayDismissed":this.W("autoplayDismissed");break;case "autoplayUpNext":this.G=a.params.videoId||null;this.W("autoplayUpNext",this.G);break;case "onAutoplayModeChanged":this.B=
a.params.autoplayMode;this.W("autoplayModeChange",this.B);"DISABLED"==this.B&&this.W("autoplayDismissed");break;case "onHasPreviousNextChanged":PMa(this,a);break;case "requestAssistedSignIn":this.W("assistedSignInRequested",a.params.authCode);break;default:$6("Unrecognized action: "+a.action)}};
g.k.kS=function(){if(this.u){var a=this.u;this.u=null;this.ac.videoId!=a&&e7(this,"getNowPlaying")}};
g.k.sN=function(){var a=3;this.Ga()||(a=0,isNaN(this.ys())?P5(this.i)&&isNaN(this.C)&&(a=1):a=2);return a};
g.k.Pp=function(a){$6("Disconnecting with "+a);b7(this);this.W("beforeDisconnect",a);1==a&&Z4();FLa(this.i,a);this.dispose()};
g.k.qN=function(){var a=this.ac;this.u&&(a=this.ac.clone(),O6(a,this.u,a.index));return P6(a)};
g.k.vS=function(a){var b=new J6(a);b.videoId&&b.videoId!=this.ac.videoId&&(this.u=b.videoId,g.jp(this.J),this.J=g.hp((0,g.D)(this.kS,this),5E3));var c=[];this.ac.listId==b.listId&&this.ac.videoId==b.videoId&&this.ac.index==b.index||c.push("remoteQueueChange");this.ac.playerState==b.playerState&&this.ac.volume==b.volume&&this.ac.muted==b.muted&&N6(this.ac)==N6(b)&&g.Dj(this.ac.trackData)==g.Dj(b.trackData)||c.push("remotePlayerChange");this.ac.reset(a);g.zb(c,function(d){this.W(d)},this)};
g.k.XF=function(){var a=this.i.G.id,b=g.bb(this.l,function(c){return"REMOTE_CONTROL"==c.type&&c.id!=a});
return b?b.id:""};
g.k.ys=function(){var a=this.i;return a.l.isActive()?a.l.l-g.Sa():NaN};
g.k.oN=function(){return this.B||"UNSUPPORTED"};
g.k.pN=function(){return this.G||""};
g.k.YL=function(){if(!isNaN(this.ys())){var a=this.i.l;a.i.yg();a.start()}};
g.k.sS=function(a,b){e7(this,a,b);GMa(this)};
g.k.TD=function(){var a=g.yo("SID","")||"",b=g.yo("SAPISID","")||"",c=g.yo("__Secure-3PAPISID","")||"";if(!a&&!b&&!c)return"";a=g.tf(g.Xe(a),2);b=g.tf(g.Xe(b),2);c=g.tf(g.Xe(c),2);return g.tf(g.Xe(a+","+b+","+c),2)};
Z6.prototype.subscribe=Z6.prototype.subscribe;Z6.prototype.unsubscribeByKey=Z6.prototype.Mf;Z6.prototype.getProxyState=Z6.prototype.sN;Z6.prototype.disconnect=Z6.prototype.Pp;Z6.prototype.getPlayerContextData=Z6.prototype.qN;Z6.prototype.setPlayerContextData=Z6.prototype.vS;Z6.prototype.getOtherConnectedRemoteId=Z6.prototype.XF;Z6.prototype.getReconnectTimeout=Z6.prototype.ys;Z6.prototype.getAutoplayMode=Z6.prototype.oN;Z6.prototype.getAutoplayVideoId=Z6.prototype.pN;Z6.prototype.reconnect=Z6.prototype.YL;
Z6.prototype.sendMessage=Z6.prototype.sS;Z6.prototype.getXsrfToken=Z6.prototype.TD;g.v(f7,Y5);g.k=f7.prototype;g.k.Vg=function(a){return this.Ef.$_gs(a)};
g.k.contains=function(a){return!!this.Ef.$_c(a)};
g.k.get=function(a){return this.Ef.$_g(a)};
g.k.start=function(){this.Ef.$_st()};
g.k.add=function(a,b,c){this.Ef.$_a(a,b,c)};
g.k.remove=function(a,b,c){this.Ef.$_r(a,b,c)};
g.k.Dx=function(a,b,c,d){this.Ef.$_un(a,b,c,d)};
g.k.va=function(){for(var a=0,b=this.i.length;a<b;++a)this.Ef.$_ubk(this.i[a]);this.i.length=0;this.Ef=null;Y5.prototype.va.call(this)};
g.k.ZL=function(){this.W("screenChange")};
g.k.oQ=function(){this.W("onlineScreenChange")};
h6.prototype.$_st=h6.prototype.start;h6.prototype.$_gspc=h6.prototype.TL;h6.prototype.$_gsppc=h6.prototype.PD;h6.prototype.$_c=h6.prototype.contains;h6.prototype.$_g=h6.prototype.get;h6.prototype.$_a=h6.prototype.add;h6.prototype.$_un=h6.prototype.Dx;h6.prototype.$_r=h6.prototype.remove;h6.prototype.$_gs=h6.prototype.Vg;h6.prototype.$_gos=h6.prototype.OD;h6.prototype.$_s=h6.prototype.subscribe;h6.prototype.$_ubk=h6.prototype.Mf;var s7=null,y7=!1,g7=null,h7=null,x7=null,l7=[];g.v(z7,g.F);g.k=z7.prototype;g.k.va=function(){g.F.prototype.va.call(this);this.i.stop();this.u.stop();this.L.stop();this.Y();var a=this.Pb;a.unsubscribe("proxyStateChange",this.bI,this);a.unsubscribe("remotePlayerChange",this.gt,this);a.unsubscribe("remoteQueueChange",this.Jw,this);a.unsubscribe("previousNextChange",this.YH,this);a.unsubscribe("nowAutoplaying",this.SH,this);a.unsubscribe("autoplayDismissed",this.pH,this);this.Pb=this.l=null};
g.k.UD=function(a,b){for(var c=[],d=1;d<arguments.length;++d)c[d-1]=arguments[d];if(2!=this.Pb.eb)if(A7(this)){if(!S6(this.Pb).isAdPlaying()||"control_seek"!==a)switch(a){case "control_toggle_play_pause":S6(this.Pb).lc()?this.Pb.pause():this.Pb.play();break;case "control_play":this.Pb.play();break;case "control_pause":this.Pb.pause();break;case "control_seek":this.J.yg(c[0],c[1]);break;case "control_subtitles_set_track":B7(this,c[0]);break;case "control_set_audio_track":this.setAudioTrack(c[0])}}else switch(a){case "control_toggle_play_pause":case "control_play":case "control_pause":c=
this.I.getCurrentTime();C7(this,0===c?void 0:c);break;case "control_seek":C7(this,c[0]);break;case "control_subtitles_set_track":B7(this,c[0]);break;case "control_set_audio_track":this.setAudioTrack(c[0])}};
g.k.jP=function(a){this.L.yg(a)};
g.k.ZS=function(a){this.UD("control_subtitles_set_track",g.Ob(a)?null:a)};
g.k.lJ=function(){var a=this.I.getOption("captions","track");g.Ob(a)||B7(this,a)};
g.k.Tb=function(a){this.l.Tb(a,this.I.getVideoData().lengthSeconds)};
g.k.WP=function(){g.Ob(this.B)||$Ma(this,this.B);this.C=!1};
g.k.bI=function(a,b){this.u.stop();2===b&&this.gJ()};
g.k.gt=function(){if(A7(this)){this.i.stop();var a=S6(this.Pb);switch(a.playerState){case 1080:case 1081:case 1084:case 1085:this.l.Pe=1;break;case 1082:case 1083:this.l.Pe=0;break;default:this.l.Pe=-1}switch(a.playerState){case 1081:case 1:this.Hb(new g.aJ(8));this.fJ();break;case 1085:case 3:this.Hb(new g.aJ(9));break;case 1083:case 0:this.Hb(new g.aJ(2));this.J.stop();this.Tb(this.I.getVideoData().lengthSeconds);break;case 1084:this.Hb(new g.aJ(4));break;case 2:this.Hb(new g.aJ(4));this.Tb(N6(a));
break;case -1:this.Hb(new g.aJ(64));break;case -1E3:this.Hb(new g.aJ(128,{errorCode:"mdx.remoteerror",errorMessage:"This video is not available for remote playback."}))}a=S6(this.Pb).trackData;var b=this.B;(a||b?a&&b&&a.trackName==b.trackName&&a.languageCode==b.languageCode&&a.languageName==b.languageName&&a.kind==b.kind:1)||(this.B=a,$Ma(this,a));a=S6(this.Pb);-1===a.volume||Math.round(this.I.getVolume())===a.volume&&this.I.isMuted()===a.muted||this.V.isActive()||this.GJ()}else ZMa(this)};
g.k.YH=function(){this.I.W("mdxpreviousnextchange")};
g.k.Jw=function(){A7(this)||ZMa(this)};
g.k.SH=function(a){isNaN(a)||this.I.W("mdxnowautoplaying",a)};
g.k.pH=function(){this.I.W("mdxautoplaycanceled")};
g.k.setAudioTrack=function(a){A7(this)&&this.Pb.setAudioTrack(this.I.getVideoData(1).videoId,a)};
g.k.seekTo=function(a,b){-1===S6(this.Pb).playerState?C7(this,a):b&&this.Pb.seekTo(a)};
g.k.GJ=function(){var a=this;if(A7(this)){var b=S6(this.Pb);this.events.dc(this.X);b.muted?this.I.mute():this.I.unMute();this.I.setVolume(b.volume);this.X=this.events.N(this.I,"onVolumeChange",function(c){YMa(a,c)})}};
g.k.fJ=function(){this.i.stop();if(!this.Pb.Ga()){var a=S6(this.Pb);a.lc()&&this.Hb(new g.aJ(8));this.Tb(N6(a));this.i.start()}};
g.k.gJ=function(){this.u.stop();this.i.stop();var a=this.Pb.u.getReconnectTimeout();2==this.Pb.eb&&!isNaN(a)&&this.u.start()};
g.k.Hb=function(a){this.u.stop();var b=this.G;if(!g.fJ(b,a)){var c=g.U(a,2);c!==g.U(this.G,2)&&this.I.Oo(c);this.G=a;bNa(this.l,b,a)}};g.v(D7,g.V);D7.prototype.Pc=function(){this.i.show()};
D7.prototype.Ab=function(){this.i.hide()};
D7.prototype.l=function(){g.HI("https://support.google.com/youtube/answer/7640706")};
D7.prototype.u=function(){M4("mdx-manual-pairing-popup-ok");this.Ab()};g.v(E7,g.V);E7.prototype.Pc=function(){this.i.show()};
E7.prototype.Ab=function(){this.i.hide()};
E7.prototype.l=function(){M4("mdx-privacy-popup-cancel");this.Ab()};
E7.prototype.u=function(){M4("mdx-privacy-popup-confirm");this.Ab()};g.v(F7,g.V);F7.prototype.l=function(a){aNa(this,a.state)};g.v(G7,g.RO);G7.prototype.C=function(){var a=this.I.getOption("remote","receivers");a&&1<a.length&&!this.I.getOption("remote","quickCast")?(this.Dm=g.Ab(a,this.i,this),g.SO(this,g.Oc(a,this.i)),a=this.I.getOption("remote","currentReceiver"),a=this.i(a),this.options[a]&&this.kh(a),this.enable(!0)):this.enable(!1)};
G7.prototype.i=function(a){return a.key};
G7.prototype.di=function(a){return"cast-selector-receiver"===a?"Cast...":this.Dm[a].name};
G7.prototype.Xe=function(a){g.RO.prototype.Xe.call(this,a);this.I.setOption("remote","currentReceiver",this.Dm[a]);this.vb.Ab()};g.v(H7,g.fM);g.k=H7.prototype;
g.k.create=function(){var a=this.player.T(),b=g.hD(a);a={device:"Desktop",app:"youtube-desktop",loadCastApiSetupScript:g.S(a.experiments,"mdx_load_cast_api_bootstrap_script"),enableDialLoungeToken:g.S(a.experiments,"enable_dial_short_lived_lounge_token"),enableCastLoungeToken:g.S(a.experiments,"enable_cast_short_lived_lounge_token")};TMa(b,a);this.subscriptions.push(g.Mq("yt-remote-before-disconnect",this.iP,this));this.subscriptions.push(g.Mq("yt-remote-connection-change",this.OQ,this));this.subscriptions.push(g.Mq("yt-remote-receiver-availability-change",
this.aI,this));this.subscriptions.push(g.Mq("yt-remote-auto-connect",this.MQ,this));this.subscriptions.push(g.Mq("yt-remote-receiver-resumed",this.LQ,this));this.subscriptions.push(g.Mq("mdx-privacy-popup-confirm",this.cS,this));this.subscriptions.push(g.Mq("mdx-privacy-popup-cancel",this.bS,this));this.subscriptions.push(g.Mq("mdx-manual-pairing-popup-ok",this.rO,this));this.aI()};
g.k.load=function(){this.player.cancelPlayback();g.fM.prototype.load.call(this);this.oh=new z7(this,this.player,this.Pb);var a=(a=XMa())?a.currentTime:0;var b=w7()?new R6(q7(),void 0):null;0==a&&b&&(a=N6(S6(b)));0!==a&&this.Tb(a);bNa(this,this.Yc,this.Yc);this.player.Tj(6)};
g.k.unload=function(){this.player.W("mdxautoplaycanceled");this.Jl=this.Ci;g.Ei(this.oh,this.Pb);this.Pb=this.oh=null;g.fM.prototype.unload.call(this);this.player.Tj(5);I7(this)};
g.k.va=function(){g.Nq(this.subscriptions);g.fM.prototype.va.call(this)};
g.k.Oj=function(a,b){for(var c=[],d=1;d<arguments.length;++d)c[d-1]=arguments[d];this.loaded&&this.oh.UD.apply(this.oh,[a].concat(g.la(c)))};
g.k.getAdState=function(){return this.Pe};
g.k.tN=function(){return this.loaded?this.oh.suggestion:null};
g.k.Dj=function(){return this.Pb?S6(this.Pb).Dj:!1};
g.k.hasNext=function(){return this.Pb?S6(this.Pb).hasNext:!1};
g.k.Tb=function(a,b){this.KG=a||0;this.player.W("progresssync",a,b)};
g.k.getCurrentTime=function(){return this.KG};
g.k.getProgressState=function(){var a=S6(this.Pb),b=this.player.getVideoData();return{allowSeeking:g.S(this.player.T().experiments,"web_player_mdx_allow_seeking_change_killswitch")?this.player.Oe():!a.isAdPlaying()&&this.player.Oe(),clipEnd:b.clipEnd,clipStart:b.clipStart,current:this.getCurrentTime(),displayedStart:-1,duration:a.getDuration(),ingestionTime:a.l?a.u+L6(a):a.u,isAtLiveHead:1>=(a.l?a.i+L6(a):a.i)-this.getCurrentTime(),loaded:a.L,seekableEnd:a.l?a.i+L6(a):a.i,seekableStart:0<a.B?a.B+
L6(a):a.B}};
g.k.nextVideo=function(){this.Pb&&this.Pb.nextVideo()};
g.k.Nw=function(){this.Pb&&this.Pb.Nw()};
g.k.iP=function(a){1===a&&(this.BB=this.Pb?S6(this.Pb):null)};
g.k.OQ=function(){var a=w7()?new R6(q7(),void 0):null;if(a){var b=this.Jl;this.loaded&&this.unload();this.Pb=a;this.BB=null;b.key!==this.Ci.key&&(this.Jl=b,this.load())}else g.Di(this.Pb),this.Pb=null,this.loaded&&(this.unload(),(a=this.BB)&&a.videoId===this.player.getVideoData().videoId&&this.player.cueVideoById(a.videoId,N6(a)));this.player.W("videodatachange","newdata",this.player.getVideoData(),3)};
g.k.aI=function(){var a=[this.Ci],b=a.concat,c=UMa();F6()&&g.Tu("yt-remote-cast-available")&&c.push({key:"cast-selector-receiver",name:"Cast..."});this.Dm=b.call(a,c);a=r7()||this.Ci;J7(this,a);this.player.La("onMdxReceiversChange")};
g.k.MQ=function(){var a=r7();J7(this,a)};
g.k.LQ=function(){this.Jl=r7()};
g.k.cS=function(){this.ot=!0;I7(this);y7=!1;s7&&u7(s7,1);s7=null};
g.k.bS=function(){this.ot=!1;I7(this);J7(this,this.Ci);this.Jl=this.Ci;y7=!1;s7=null;this.player.playVideo()};
g.k.rO=function(){this.hw=!0;I7(this);g.Su("yt-remote-manual-pairing-warning-shown",!0,2592E3);y7=!1;s7&&u7(s7,1);s7=null};
g.k.Je=function(a,b){switch(a){case "casting":return this.loaded;case "receivers":return this.Dm;case "currentReceiver":return b&&("cast-selector-receiver"===b.key?H6():J7(this,b)),this.loaded?this.Jl:this.Ci;case "quickCast":return 2===this.Dm.length&&"cast-selector-receiver"===this.Dm[1].key?(b&&H6(),!0):!1}};
g.k.rC=function(){this.Pb.rC()};
g.k.Th=function(){return!1};
g.k.getOptions=function(){return["casting","receivers","currentReceiver","quickCast"]};g.lM.remote=H7;})(_yt_player);
